[workspace]
resolver = "3"
members = [
    "crates/adventuresim-core",
    "crates/adventuresim-stdb-module",
    "crates/adventuresim-stdb-client",
    "crates/adventuresim-tactical-core",
    "crates/adventuresim-tactical-netcode",
    "crates/adventuresim-tactical-client",
    "crates/adventuresim-tactical-server",
    "crates/adventuresim-tactical-server-dispatcher", 
    "crates/adventuresim-character-creator",
]
exclude = ["/wiki", "/utils"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/adventure-simulator-group/adventure-simulator"
license = "GPL-3.0"

[workspace.dependencies]
adventuresim-tactical-netcode = { version = "0.1.0", default-features = false }
adventuresim-tactical-core = { version = "0.1.0" }
adventuresim-stdb-client = { version = "0.1.0" }
adventuresim-core = { version = "0.1.0" }

bevy = { version = "0.18.0", default-features = false, features = [
  "reflect_auto_register",
  "bevy_log",
] }
lightyear = { version = "0.26.4", default-features = false }
avian3d = { version = "0.6.0-rc.1", default-features = false, features = [
    "3d",
    "f32",
    "default-collider"
] }
bevy_ahoy = { version = "0.1.0-rc.1", default-features = false, features = ["serialize"] }
bevy_enhanced_input = { version = "0.23", default-features = false }
bevy_flair = "0.7"
noiz = "0.4.0"

serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
console_error_panic_hook = "0.1.7"
async-compat = "0.2.5"
cfg-if = "1.0"
clap = { version = "4.5.60", features = ["derive", "env"] }
tracing = "0.1.44"
rand = "0.9"
getrandom = { version = "0.3", features = ["wasm_js"] }
getrandom_02 = { version = "0.2", features = ["js"], package = "getrandom" }
thiserror = "2.0.18"
wasm-bindgen = "=0.2.106"
spacetimedb = "=1.11"
spacetimedb-sdk = "=1.11"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[patch.crates-io]
adventuresim-tactical-netcode = { path = "crates/adventuresim-tactical-netcode" }
adventuresim-tactical-core = { path = "crates/adventuresim-tactical-core" }
adventuresim-stdb-client = { path = "crates/adventuresim-stdb-client" }
adventuresim-core = { path = "crates/adventuresim-core" }

# https://github.com/cBournhonesque/lightyear/pull/1405
# https://github.com/cBournhonesque/lightyear/pull/1420
lightyear = { git = "https://github.com/barsoosayque/lightyear", branch = "avian-0.6.0-rc.1" }
# https://github.com/janhohenheim/bevy_ahoy/pull/66
# https://github.com/janhohenheim/bevy_ahoy/pull/67
# https://github.com/janhohenheim/bevy_ahoy/pull/76
bevy_ahoy = { git = "https://github.com/barsoosayque/bevy_ahoy", branch = "adventuresim" }
