[workspace]
resolver = "3"
members = [
    "crates/adventuresim-core",
    "crates/adventuresim-world-schema",
    "crates/adventuresim-world-import",
    "crates/adventuresim-stdb-module",
    "crates/adventuresim-stdb-client",
    "crates/adventuresim-tactical-core",
    "crates/adventuresim-tactical-netcode",
    "crates/adventuresim-tactical-client",
    "crates/adventuresim-tactical-server",
    "crates/adventuresim-tactical-server-dispatcher", 
    "crates/adventuresim-character-creator",
    "crates/strategic-web",
]
exclude = ["/wiki", "/utils"]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/adventure-simulator-group/adventure-simulator"
license = "GPL-3.0"

[workspace.dependencies]
adventuresim-tactical-netcode = { version = "0.1.0", default-features = false }
adventuresim-tactical-core = { version = "0.1.0" }
adventuresim-stdb-client = { version = "0.1.0" }
adventuresim-core = { version = "0.1.0" }
adventuresim-world-schema = { version = "0.1.0", path = "crates/adventuresim-world-schema" }

bevy = { version = "0.18.0", default-features = false, features = [
  "reflect_auto_register",
  "bevy_log",
  "serialize",
] }
aeronet = { version = "0.20.0" }
aeronet_replicon = { version = "0.20.0", default-features = false }
aeronet_websocket = { version = "0.20.0", default-features = false }
bevy_replicon = { version = "0.39.4", default-features = false, features = ["client", "server"] }
avian3d = { version = "0.6.0", default-features = false, features = [
    "3d",
    "f32",
    "parry-f32",
    "parallel",
    "default-collider",
] }
bevy_ahoy = { version = "0.1.0-rc.1", default-features = false, features = ["serialize"] }
bevy_enhanced_input = { version = "0.23", default-features = false }
bevy_flair = "0.7"
noiz = "0.4.0"

serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
console_error_panic_hook = "0.1.7"
async-compat = "0.2.5"
cfg-if = "1.0"
clap = { version = "4.5.60", features = ["derive", "env"] }
tracing = "0.1.44"
rand = "0.9"
getrandom = { version = "0.3", features = ["wasm_js"] }
getrandom_02 = { version = "0.2", features = ["js"], package = "getrandom" }
thiserror = "2.0.18"
tiff = "0.11.3"
csv = "1.3"
dbase = "0.8.0"
blake3 = "1"
geo = "0.33.1"
proj4rs = { version = "0.1.10", default-features = false }
shapefile = { version = "0.9.0", features = ["geo-types"] }
wasm-bindgen = "=0.2.108"
spacetimedb = "=2.6.1"
spacetimedb-sdk = "=2.6.1"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[patch.crates-io]
adventuresim-tactical-netcode = { path = "crates/adventuresim-tactical-netcode" }
adventuresim-tactical-core = { path = "crates/adventuresim-tactical-core" }
adventuresim-stdb-client = { path = "crates/adventuresim-stdb-client" }
adventuresim-core = { path = "crates/adventuresim-core" }

# https://github.com/janhohenheim/bevy_ahoy/pull/66
bevy_ahoy = { git = "https://github.com/barsoosayque/bevy_ahoy", branch = "adventuresim" }
# https://github.com/avianphysics/avian/pull/977
avian3d = { git = "https://github.com/barsoosayque/avian", branch = "adventuresim" }

[profile.win-dev]
inherits = "dev"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
strip = "debuginfo"
