[workspace]
resolver = "3"
members = [
    "crates/adventure-simulator-net",
    "crates/adventure-simulator-client",
    "crates/adventure-simulator-core",
    "crates/character-creator",
    "crates/strategic-db",
    "crates/strategic-db-client",
    "crates/tactical-server",
    "crates/tactical-spawner",
]
exclude = ["/wiki", "/utils"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/adventure-simulator-group/adventure-simulator"
license = "GPL-3.0"

[workspace.dependencies]
adventure-simulator-net = { version = "0.1.0", default-features = false }
adventure-simulator-core = { version = "0.1.0" }

bevy = { version = "0.17.3", default-features = false }
lightyear = { version = "0.25.5", default-features = false }
lightyear_frame_interpolation = { version = "0.25.5", default-features = false }
avian3d = { version = "0.4", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
console_error_panic_hook = "0.1.7"
async-compat = "0.2.3"
cfg-if = "1.0"
clap = { version = "4.5.4", features = ["derive", "env"] }
tracing = "0.1.40"
rand = "0.9"
getrandom = { version = "0.3", features = ["wasm_js"] }
getrandom_02 = { version = "0.2", features = ["js"], package = "getrandom" }
bevy-inspector-egui = { version = "0.35", default-features = false, features = [
    "bevy_pbr",
    "bevy_image",
    "bevy_render",
    "egui_open_url",
] }
bevy_egui = { version = "0.38", default-features = false, features = [
    "open_url",
    "default_fonts",
    "render",
] }
bevy_ahoy = { git = "https://github.com/janhohenheim/bevy_ahoy" }
bevy_enhanced_input = "0.20"
toml = "0.9.8"
thiserror = "2.0.17"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[patch.crates-io]
adventure-simulator-net = { path = "crates/adventure-simulator-net" }
adventure-simulator-core = { path = "crates/adventure-simulator-core" }
# bevy_ahoy requires bleeding edge avian3d
avian3d = { git = "https://github.com/avianphysics/avian" }
