[package]
name = "adventuresim-mhr"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/adventure-simulator-group/fabelgeist"
license = "GPL-3.0"

[dependencies]
adventuresim-fbx = { path = "../adventuresim-fbx" }
anyhow = "1"
burn = { git = "https://github.com/tracel-ai/burn", rev = "b1502de8b396e7c575981d8df9fc84099619f458", default-features = false, features = [
    "std",
    "wgpu",
] }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
memmap2 = "0.9"

[workspace]

