[package]
name = "marching-cubes-plugin"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_egui.workspace = true
distance-field-plugin.workspace = true
distance-field.workspace = true
anyhow = "1.0"
marching-cubes = { workspace = true, features = ["bevy"] }
pollster = "0.4"
gpu-runtime = { workspace = true }
bytemuck = { version = "1.15", features = ["derive"] }
bevy_mesh = { workspace = true }

[lints]
workspace = true
