[package]
name = "strategic-db"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
spacetimedb.workspace = true
petname = { version = "2.0.2", default-features = false, features = ["default-words"] }
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
