[package]
name = "adventure-simulator-client"
description = "Adventure Simulator: Wasm game client"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true, default-features = true, features = [] }
avian3d.workspace = true
bevy_ahoy.workspace = true
bevy_enhanced_input.workspace = true

[target."cfg(target_family = \"wasm\")".dependencies]
console_error_panic_hook.workspace = true

[package.metadata.bevy_cli.web]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

[lints]
workspace = true

[[bin]]
name = "adventure-simulator-client"
doc = false
