[package]
name = "adventuresim-world-import"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
[dependencies]
adventuresim-world-schema.workspace = true
blake3.workspace = true
clap.workspace = true
csv.workspace = true
dbase.workspace = true
geo.workspace = true
geozero.workspace = true
proj4rs.workspace = true
rayon.workspace = true
rusqlite.workspace = true
html-escape.workspace = true
image.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
netcdf-reader.workspace = true
shapefile.workspace = true
thiserror.workspace = true
tiff.workspace = true
tiny-skia.workspace = true
zip.workspace = true

[lints]
workspace = true
