[package]
name = "tactical-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tactical-server"
path = "src/main.rs"

[dependencies]
# Bevy + Lightyear
bevy = { workspace = true, default-features = false, features = ["multi_threaded"] }
adventure-simulator-net = { workspace = true, features = ["server"] }

# SpacetimeDB client
strategic-db-client = { path = "../strategic-db-client" }

# CLI
clap = { workspace = true }
