[package]
name = "tactical-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tactical-server"
path = "src/main.rs"

[dependencies]
noiz.workspace = true

# Bevy + Lightyear
bevy = { workspace = true, features = ["multi_threaded"] }
adventure-simulator-net = { workspace = true, features = ["server"] }
adventure-simulator-core.workspace = true

# SpacetimeDB client
strategic-db-client.workspace = true 
spacetimedb-sdk.workspace = true

# CLI
clap = { workspace = true }
