[package]
name = "tactical-spawner"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tactical-spawner"
path = "src/main.rs"

[dependencies]
# SpacetimeDB SDK
strategic-stdb-client = { path = "../strategic-stdb-client" }

# CLI
clap = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
