[package]
name = "adventuresim-tactical-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "adventuresim-tactical-server"
path = "src/main.rs"

[dependencies]
noiz.workspace = true

# Bevy + Lightyear
bevy = { workspace = true, features = ["multi_threaded"] }
adventuresim-tactical-netcode = { workspace = true, features = ["server"] }
adventuresim-tactical-core.workspace = true

# CLI
clap = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
