use adventuresim_strategic_sim::*;
use clap::{Parser, Subcommand, ValueEnum};
use std::{
    fs,
    io::Read,
    path::{Path, PathBuf},
};

#[derive(Parser)]
#[command(about = "Deterministic strategic NPC balance simulator")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Evaluate generated investigation quests through an observer-safe player agent.
    QuestEval {
        #[arg(long, value_enum, default_value_t = EvalPolicyArg::Scripted)]
        policy: EvalPolicyArg,
        #[arg(long, default_value_t = 41)]
        seed: u64,
        #[arg(long, default_value_t = 4)]
        cases_per_template: u32,
        /// Public player-visible trace and aggregate metrics.
        #[arg(long)]
        public_output: PathBuf,
        /// Separate developer-only generator truth and factor audit.
        #[arg(long)]
        developer_output: PathBuf,
        #[arg(long)]
        endpoint: Option<String>,
        #[arg(long, default_value = "gpt-4.1-nano")]
        model: String,
        /// Name of the environment variable containing the key; never the key itself.
        #[arg(long, default_value = "OPENAI_API_KEY")]
        api_key_env: String,
        /// Required before any paid/provider network request.
        #[arg(long, default_value_t = false)]
        allow_network: bool,
    },
    /// Replay previously validated opaque actions for one deterministic fixture.
    QuestEvalReplay {
        #[arg(long)]
        fixture: PathBuf,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Generate profiles and run canonical settlement downtime.
    Run {
        #[arg(long)]
        config: Option<PathBuf>,
        #[arg(long)]
        output: Option<PathBuf>,
        #[arg(long, default_value_t = 1)]
        seed: u64,
        #[arg(long, default_value_t = 100)]
        population: u32,
        #[arg(long, default_value_t = 1095)]
        days: u32,
    },
    /// Rerun a report's recorded manifest and verify its digest.
    Replay {
        #[arg(long)]
        report: PathBuf,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Run a matched labor/thievery pair with common initial circumstances.
    Matched {
        #[arg(long, default_value_t = 1)]
        seed: u64,
        #[arg(long, default_value_t = 365)]
        days: u32,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Exercise the complete strategic loop against an owned disposable local database.
    CoreLoop {
        #[arg(long, default_value = "http://127.0.0.1:3000")]
        host: String,
        /// Must be a unique `adventuresim-sim-*` database published for this run.
        #[arg(long)]
        database: String,
        #[arg(long, default_value_t = 1)]
        seed: u64,
        #[arg(long, default_value_t = 2)]
        population: u32,
        #[arg(long, default_value_t = 1)]
        cycles: u32,
        #[arg(long, default_value_t = 365)]
        duration_days: u32,
        #[arg(long, default_value_t = 2)]
        party_size: u32,
        /// Unpredictable nonce generated by the owning launcher.
        #[arg(long)]
        run_nonce: String,
        #[arg(long)]
        output: Option<PathBuf>,
    },
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum EvalPolicyArg {
    Scripted,
    Mock,
    Openai,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    let command = match cli.command {
        Command::QuestEval {
            policy,
            seed,
            cases_per_template,
            public_output,
            developer_output,
            endpoint,
            model,
            api_key_env,
            allow_network,
        } => {
            if !(1..=500).contains(&cases_per_template) {
                return Err("cases_per_template must be 1..=500".into());
            }
            validate_distinct_output_paths(&public_output, &developer_output)?;
            let configs = golden_suite(seed, cases_per_template);
            let limits = EvalLimits {
                max_cases: cases_per_template
                    .checked_mul(2)
                    .ok_or("case count overflow")?,
                ..EvalLimits::default()
            };
            let mut policy: Box<dyn QuestPolicy> = match policy {
                EvalPolicyArg::Scripted => Box::new(ScriptedPolicy::default()),
                EvalPolicyArg::Mock => Box::new(MockLlmPolicy),
                EvalPolicyArg::Openai => {
                    let config = ProviderConfig {
                        endpoint: endpoint.unwrap_or_else(|| ProviderConfig::default().endpoint),
                        model,
                        api_key_env,
                        allow_network,
                        ..ProviderConfig::default()
                    };
                    // Construction validates opt-in and credential before case generation.
                    Box::new(OpenAiCompatiblePolicy::new(config)?)
                }
            };
            let bundle = evaluate_cases(&configs, policy.as_mut(), &limits)?;
            fs::write(&public_output, serde_json::to_vec_pretty(&bundle.public)?)?;
            fs::write(
                &developer_output,
                serde_json::to_vec_pretty(&bundle.developer)?,
            )?;
            eprintln!(
                "quest evaluation: {}/{} solved; public={} developer={}",
                bundle.public.metrics.solved,
                bundle.public.metrics.cases,
                public_output.display(),
                developer_output.display()
            );
            return Ok(());
        }
        Command::QuestEvalReplay { fixture, output } => {
            let recorded: ReplayCase = serde_json::from_slice(&read_bounded(&fixture)?)?;
            let trace = replay_case(&recorded)?;
            let json = serde_json::to_vec_pretty(&trace)?;
            if let Some(path) = output {
                fs::write(path, json)?;
            } else {
                println!("{}", String::from_utf8(json)?);
            }
            return Ok(());
        }
        command => command,
    };
    if let Command::CoreLoop {
        host,
        database,
        seed,
        population,
        cycles,
        duration_days,
        party_size,
        run_nonce,
        output,
    } = command
    {
        let report = run_core_loop(CoreLoopConfig {
            host,
            database,
            seed,
            population,
            cycles,
            duration_days,
            party_size,
            run_nonce,
        })?;
        let json = serde_json::to_vec_pretty(&report)?;
        if let Some(path) = output {
            fs::write(path, json)?;
        } else {
            println!("{}", String::from_utf8(json)?);
        }
        eprintln!(
            "authoritative core loop: {} completed / {} attempted, {} quest defeats, {} encounters ({} encounter defeats, {} wipes), {} camps, {} upgrades",
            report.metrics.quests_completed,
            report.metrics.quests_attempted,
            report.metrics.defeats,
            report.metrics.encounters,
            report.metrics.encounter_defeats,
            report.metrics.encounter_wipes,
            report.metrics.camp_stops,
            report.metrics.equipment_upgrades,
        );
        return Ok(());
    }
    let report = match command {
        Command::Run {
            config,
            output,
            seed,
            population,
            days,
        } => {
            let config = if let Some(path) = config {
                serde_json::from_slice(&read_bounded(&path)?)?
            } else {
                SimulationConfig {
                    seed,
                    population,
                    days,
                    max_decisions: u64::from(population)
                        .checked_mul(u64::from(days))
                        .ok_or("decision count overflow")?,
                    ..SimulationConfig::default()
                }
            };
            emit(run(config)?, output)?
        }
        Command::Replay { report, output } => {
            let recorded: SimulationReport = serde_json::from_slice(&read_bounded(&report)?)?;
            let computed = digest(&recorded)?;
            if computed != recorded.canonical_digest {
                return Err(format!(
                    "recorded report digest is invalid: stored {}, computed {computed}",
                    recorded.canonical_digest
                )
                .into());
            }
            let rerun = replay(recorded.manifest.clone())?;
            if rerun.canonical_digest != recorded.canonical_digest {
                return Err("replay digest differs".into());
            }
            emit(rerun, output)?
        }
        Command::Matched { seed, days, output } => {
            let (a, b) = matched_activity_pair(
                seed,
                0,
                ActivityPreference::Labor,
                ActivityPreference::Thievery,
            );
            let mut b = b;
            b.agent_id = 1;
            let config = SimulationConfig {
                seed,
                population: 2,
                days,
                max_decisions: 2_u64
                    .checked_mul(u64::from(days))
                    .ok_or("decision count overflow")?,
                ..SimulationConfig::default()
            };
            emit(run_profiles(config, vec![a, b])?, output)?
        }
        Command::CoreLoop { .. } | Command::QuestEval { .. } | Command::QuestEvalReplay { .. } => {
            unreachable!()
        }
    };
    eprintln!("{}", human_summary(&report));
    Ok(())
}

fn validate_distinct_output_paths(
    public_output: &Path,
    developer_output: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let normalize = |path: &Path| -> Result<PathBuf, Box<dyn std::error::Error>> {
        if path.exists() {
            Ok(fs::canonicalize(path)?)
        } else {
            Ok(std::env::current_dir()?.join(path))
        }
    };
    if normalize(public_output)? == normalize(developer_output)? {
        return Err("public and developer evaluation outputs must be distinct paths".into());
    }
    Ok(())
}

fn read_bounded(path: &Path) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let mut bytes = Vec::new();
    fs::File::open(path)?
        .take(MAX_INPUT_BYTES + 1)
        .read_to_end(&mut bytes)?;
    validate_input_len(bytes.len() as u64)?;
    Ok(bytes)
}

fn emit(
    report: SimulationReport,
    output: Option<PathBuf>,
) -> Result<SimulationReport, Box<dyn std::error::Error>> {
    let json = serde_json::to_vec_pretty(&report)?;
    if let Some(path) = output {
        fs::write(path, json)?;
    } else {
        println!("{}", String::from_utf8(json)?);
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn public_and_developer_outputs_must_differ() {
        let path = PathBuf::from("quest-eval-same-output.json");
        assert!(validate_distinct_output_paths(&path, &path).is_err());
    }
}
