use adventuresim_strategic_sim::*;
use clap::{Parser, Subcommand, ValueEnum};
use std::{
    fs,
    io::Read,
    path::{Path, PathBuf},
};

#[derive(Parser)]
#[command(about = "Deterministic strategic NPC balance simulator")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Generate profiles and run canonical settlement downtime.
    Run {
        #[arg(long)]
        config: Option<PathBuf>,
        #[arg(long)]
        output: Option<PathBuf>,
        #[arg(long, default_value_t = 1)]
        seed: u64,
        #[arg(long, default_value_t = 100)]
        population: u32,
        #[arg(long, default_value_t = 1095)]
        days: u32,
    },
    /// Rerun a report's recorded manifest and verify its digest.
    Replay {
        #[arg(long)]
        report: PathBuf,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Run a matched labor/thievery pair with common initial circumstances.
    Matched {
        #[arg(long, default_value_t = 1)]
        seed: u64,
        #[arg(long, default_value_t = 365)]
        days: u32,
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Exercise the complete strategic loop against an owned disposable local database.
    CoreLoop {
        #[arg(long, default_value = "http://127.0.0.1:3000")]
        host: String,
        /// Must be a unique `adventuresim-sim-*` database published for this run.
        #[arg(long)]
        database: String,
        #[arg(long, default_value_t = 1)]
        seed: u64,
        #[arg(long, default_value_t = 2)]
        population: u32,
        #[arg(long, default_value_t = 1)]
        cycles: u32,
        #[arg(long, default_value_t = 365)]
        duration_days: u32,
        #[arg(long, default_value_t = 2)]
        party_size: u32,
        /// Unpredictable nonce generated by the owning launcher.
        #[arg(long)]
        run_nonce: String,
        #[arg(long)]
        output: Option<PathBuf>,
        /// Markdown anthology persisted from authoritative server intervention rows.
        #[arg(long, default_value = "npc-adventurer-stories.md")]
        npc_stories_output: PathBuf,
        /// The server-scripted policy is deterministic and requires no model.
        #[arg(long, value_enum, default_value_t = NpcStrategyPolicyArg::ServerScripted)]
        npc_strategy_policy: NpcStrategyPolicyArg,
        #[arg(long)]
        npc_endpoint: Option<String>,
        #[arg(long, default_value = "gpt-4.1-nano")]
        npc_model: String,
        #[arg(long, default_value = "OPENAI_API_KEY")]
        npc_api_key_env: String,
        #[arg(long, default_value_t = false)]
        npc_allow_network: bool,
    },
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum NpcStrategyPolicyArg {
    ServerScripted,
    Openai,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    let command = cli.command;
    if let Command::CoreLoop {
        host,
        database,
        seed,
        population,
        cycles,
        duration_days,
        party_size,
        run_nonce,
        output,
        npc_stories_output,
        npc_strategy_policy,
        npc_endpoint,
        npc_model,
        npc_api_key_env,
        npc_allow_network,
    } = command
    {
        if let Some(json_output) = &output {
            validate_distinct_output_paths(&[json_output, &npc_stories_output])?;
        }
        let policy: Option<Box<dyn QuestPolicy>> = match npc_strategy_policy {
            NpcStrategyPolicyArg::ServerScripted => None,
            NpcStrategyPolicyArg::Openai => {
                Some(Box::new(OpenAiCompatiblePolicy::new(ProviderConfig {
                    endpoint: npc_endpoint.unwrap_or_else(|| ProviderConfig::default().endpoint),
                    model: npc_model,
                    api_key_env: npc_api_key_env,
                    allow_network: npc_allow_network,
                    ..ProviderConfig::default()
                })?))
            }
        };
        let report = run_core_loop_with_npc_policy(
            CoreLoopConfig {
                host,
                database,
                seed,
                population,
                cycles,
                duration_days,
                party_size,
                run_nonce,
            },
            policy,
        )?;
        fs::write(
            &npc_stories_output,
            report.npc_intervention_stories_markdown.as_bytes(),
        )?;
        let json = serde_json::to_vec_pretty(&report)?;
        if let Some(path) = output {
            fs::write(path, json)?;
        } else {
            println!("{}", String::from_utf8(json)?);
        }
        eprintln!(
            "authoritative core loop: {} completed / {} attempted, {} quest defeats, {} encounters ({} encounter defeats, {} wipes), {} camps, {} upgrades",
            report.metrics.quests_completed,
            report.metrics.quests_attempted,
            report.metrics.defeats,
            report.metrics.encounters,
            report.metrics.encounter_defeats,
            report.metrics.encounter_wipes,
            report.metrics.camp_stops,
            report.metrics.equipment_upgrades,
        );
        eprintln!("NPC intervention stories: {}", npc_stories_output.display());
        return Ok(());
    }
    let report = match command {
        Command::Run {
            config,
            output,
            seed,
            population,
            days,
        } => {
            let config = if let Some(path) = config {
                serde_json::from_slice(&read_bounded(&path)?)?
            } else {
                SimulationConfig {
                    seed,
                    population,
                    days,
                    max_decisions: u64::from(population)
                        .checked_mul(u64::from(days))
                        .ok_or("decision count overflow")?,
                    ..SimulationConfig::default()
                }
            };
            emit(run(config)?, output)?
        }
        Command::Replay { report, output } => {
            let recorded: SimulationReport = serde_json::from_slice(&read_bounded(&report)?)?;
            let computed = digest(&recorded)?;
            if computed != recorded.canonical_digest {
                return Err(format!(
                    "recorded report digest is invalid: stored {}, computed {computed}",
                    recorded.canonical_digest
                )
                .into());
            }
            let rerun = replay(recorded.manifest.clone())?;
            if rerun.canonical_digest != recorded.canonical_digest {
                return Err("replay digest differs".into());
            }
            emit(rerun, output)?
        }
        Command::Matched { seed, days, output } => {
            let (a, b) = matched_activity_pair(
                seed,
                0,
                ActivityPreference::Labor,
                ActivityPreference::Thievery,
            );
            let mut b = b;
            b.agent_id = 1;
            let config = SimulationConfig {
                seed,
                population: 2,
                days,
                max_decisions: 2_u64
                    .checked_mul(u64::from(days))
                    .ok_or("decision count overflow")?,
                ..SimulationConfig::default()
            };
            emit(run_profiles(config, vec![a, b])?, output)?
        }
        Command::CoreLoop { .. } => unreachable!(),
    };
    eprintln!("{}", human_summary(&report));
    Ok(())
}

fn validate_distinct_output_paths(paths: &[&Path]) -> Result<(), Box<dyn std::error::Error>> {
    let normalize = |path: &Path| -> Result<PathBuf, Box<dyn std::error::Error>> {
        let absolute = if path.is_absolute() {
            path.to_path_buf()
        } else {
            std::env::current_dir()?.join(path)
        };
        // `canonicalize` cannot normalize a not-yet-created output. Collapse
        // `.` and `..` lexically first, then resolve existing aliases/symlinks.
        let lexical = lexical_normalize(&absolute);
        if lexical.exists() {
            Ok(lexical_normalize(&fs::canonicalize(lexical)?))
        } else {
            Ok(lexical)
        }
    };
    let normalized = paths
        .iter()
        .map(|path| normalize(path))
        .collect::<Result<Vec<_>, _>>()?;
    for (index, left) in normalized.iter().enumerate() {
        for right in normalized.iter().skip(index + 1) {
            let same = if cfg!(windows) {
                left.to_string_lossy()
                    .eq_ignore_ascii_case(&right.to_string_lossy())
            } else {
                left == right
            };
            if same {
                return Err("evaluation outputs must use distinct paths".into());
            }
        }
    }
    Ok(())
}

fn lexical_normalize(path: &Path) -> PathBuf {
    use std::path::Component;

    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            Component::RootDir => normalized.push(component.as_os_str()),
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            Component::Normal(segment) => normalized.push(segment),
        }
    }
    normalized
}

fn read_bounded(path: &Path) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let mut bytes = Vec::new();
    fs::File::open(path)?
        .take(MAX_INPUT_BYTES + 1)
        .read_to_end(&mut bytes)?;
    validate_input_len(bytes.len() as u64)?;
    Ok(bytes)
}

fn emit(
    report: SimulationReport,
    output: Option<PathBuf>,
) -> Result<SimulationReport, Box<dyn std::error::Error>> {
    let json = serde_json::to_vec_pretty(&report)?;
    if let Some(path) = output {
        fs::write(path, json)?;
    } else {
        println!("{}", String::from_utf8(json)?);
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn duplicate_outputs_must_differ() {
        let path = PathBuf::from("simulation-output.json");
        assert!(validate_distinct_output_paths(&[&path, &path]).is_err());
    }

    #[test]
    fn nonexistent_lexical_aliases_are_rejected() {
        let canonical = PathBuf::from("simulation-output.json");
        let alias = PathBuf::from("new-output-directory")
            .join("..")
            .join("simulation-output.json");
        assert!(validate_distinct_output_paths(&[&canonical, &alias]).is_err());
    }

    #[test]
    fn core_report_and_npc_stories_must_differ() {
        let report = PathBuf::from("core-loop-report.json");
        let stories = PathBuf::from("npc-adventurer-stories.md");
        assert!(validate_distinct_output_paths(&[&report, &stories]).is_ok());
        assert!(validate_distinct_output_paths(&[&stories, &stories]).is_err());
    }
}
