[package]
name = "adventure-simulator-net"
description = "Adventure Simulator: Server/Client netcode library"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["server", "client"]
server = ["lightyear/server", "lightyear/client"]
client = ["lightyear/client"]

[dependencies]
adventure-simulator-core.workspace = true
lightyear = { "workspace" = true, features = [
  "replication",
  "netcode",
  "udp",
  "input_bei",
] }
async-compat.workspace = true
serde.workspace = true
bevy = { workspace = true, features = [
  "bevy_state",
  "bevy_log",
  "reflect_auto_register",
] }
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[target."cfg(target_family = \"wasm\")".dependencies]
console_error_panic_hook.workspace = true
rand.workspace = true
getrandom.workspace = true
getrandom_02.workspace = true

[lints]
workspace = true
