// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
#[derive(Copy, Eq, Hash)]
pub enum AgriculturalLimitation {
    None,

    Gravelly,

    Stony,

    ShallowRock,

    Concretionary,

    CementedCalcic,

    Saline,

    Sodic,

    GlacierOrSnow,

    Disturbed,

    Fragic,

    Drained,

    Flooded,

    Eroded,

    ShallowWaterTable,

}



impl __sdk::InModule for AgriculturalLimitation {
    type Module = super::RemoteModule;
}

