// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::journey_route_plan_type::JourneyRoutePlan;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApprovePartyActionRequestPlannedArgs {
    pub leader_id: u64,
    pub request_id: u64,
    pub route: JourneyRoutePlan,
}

impl From<ApprovePartyActionRequestPlannedArgs> for super::Reducer {
    fn from(args: ApprovePartyActionRequestPlannedArgs) -> Self {
        Self::ApprovePartyActionRequestPlanned {
            leader_id: args.leader_id,
            request_id: args.request_id,
            route: args.route,
        }
    }
}

impl __sdk::InModule for ApprovePartyActionRequestPlannedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `approve_party_action_request_planned`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait approve_party_action_request_planned {
    /// Request that the remote module invoke the reducer `approve_party_action_request_planned` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`approve_party_action_request_planned:approve_party_action_request_planned_then`] to run a callback after the reducer completes.
    fn approve_party_action_request_planned(
        &self,
        leader_id: u64,
        request_id: u64,
        route: JourneyRoutePlan,
    ) -> __sdk::Result<()> {
        self.approve_party_action_request_planned_then(leader_id, request_id, route, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `approve_party_action_request_planned` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn approve_party_action_request_planned_then(
        &self,
        leader_id: u64,
        request_id: u64,
        route: JourneyRoutePlan,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl approve_party_action_request_planned for super::RemoteReducers {
    fn approve_party_action_request_planned_then(
        &self,
        leader_id: u64,
        request_id: u64,
        route: JourneyRoutePlan,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ApprovePartyActionRequestPlannedArgs {
                leader_id,
                request_id,
                route,
            },
            callback,
        )
    }
}
