// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_exposure_type::CharacterExposure;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_character_exposures`.
///
/// Obtain a handle from the [`BackendCharacterExposuresTableAccess::backend_character_exposures`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_character_exposures()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_character_exposures().on_insert(...)`.
pub struct BackendCharacterExposuresTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterExposure>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_character_exposures`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendCharacterExposuresTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendCharacterExposuresTableHandle`], which mediates access to the table `backend_character_exposures`.
    fn backend_character_exposures(&self) -> BackendCharacterExposuresTableHandle<'_>;
}

impl BackendCharacterExposuresTableAccess for super::RemoteTables {
    fn backend_character_exposures(&self) -> BackendCharacterExposuresTableHandle<'_> {
        BackendCharacterExposuresTableHandle {
            imp: self
                .imp
                .get_table::<CharacterExposure>("backend_character_exposures"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendCharacterExposuresInsertCallbackId(__sdk::CallbackId);
pub struct BackendCharacterExposuresDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendCharacterExposuresTableHandle<'ctx> {
    type Row = CharacterExposure;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterExposure> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendCharacterExposuresInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterExposuresInsertCallbackId {
        BackendCharacterExposuresInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendCharacterExposuresInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendCharacterExposuresDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterExposuresDeleteCallbackId {
        BackendCharacterExposuresDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendCharacterExposuresDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterExposure>("backend_character_exposures");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterExposure>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterExposure>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterExposure`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_character_exposuresQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterExposure`.
    fn backend_character_exposures(&self) -> __sdk::__query_builder::Table<CharacterExposure>;
}

impl backend_character_exposuresQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_character_exposures(&self) -> __sdk::__query_builder::Table<CharacterExposure> {
        __sdk::__query_builder::Table::new("backend_character_exposures")
    }
}
