// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::backend_physical_evidence_type::BackendPhysicalEvidence;

/// Table handle for the table `backend_physical_evidence`.
///
/// Obtain a handle from the [`BackendPhysicalEvidenceTableAccess::backend_physical_evidence`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_physical_evidence()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_physical_evidence().on_insert(...)`.
pub struct BackendPhysicalEvidenceTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendPhysicalEvidence>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_physical_evidence`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendPhysicalEvidenceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendPhysicalEvidenceTableHandle`], which mediates access to the table `backend_physical_evidence`.
    fn backend_physical_evidence(&self) -> BackendPhysicalEvidenceTableHandle<'_>;
}

impl BackendPhysicalEvidenceTableAccess for super::RemoteTables {
    fn backend_physical_evidence(&self) -> BackendPhysicalEvidenceTableHandle<'_> {
        BackendPhysicalEvidenceTableHandle {
            imp: self.imp.get_table::<BackendPhysicalEvidence>("backend_physical_evidence"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendPhysicalEvidenceInsertCallbackId(__sdk::CallbackId);
pub struct BackendPhysicalEvidenceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendPhysicalEvidenceTableHandle<'ctx> {
    type Row = BackendPhysicalEvidence;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = BackendPhysicalEvidence> + '_ { self.imp.iter() }

    type InsertCallbackId = BackendPhysicalEvidenceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysicalEvidenceInsertCallbackId {
        BackendPhysicalEvidenceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendPhysicalEvidenceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendPhysicalEvidenceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendPhysicalEvidenceDeleteCallbackId {
        BackendPhysicalEvidenceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendPhysicalEvidenceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<BackendPhysicalEvidence>("backend_physical_evidence");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendPhysicalEvidence>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<BackendPhysicalEvidence>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `BackendPhysicalEvidence`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait backend_physical_evidenceQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `BackendPhysicalEvidence`.
            fn backend_physical_evidence(&self) -> __sdk::__query_builder::Table<BackendPhysicalEvidence>;
        }

        impl backend_physical_evidenceQueryTableAccess for __sdk::QueryTableAccessor {
            fn backend_physical_evidence(&self) -> __sdk::__query_builder::Table<BackendPhysicalEvidence> {
                __sdk::__query_builder::Table::new("backend_physical_evidence")
            }
        }

