// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::weapon_holder_instance_type::WeaponHolderInstance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_weapon_holder_instances`.
///
/// Obtain a handle from the [`BackendWeaponHolderInstancesTableAccess::backend_weapon_holder_instances`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_weapon_holder_instances()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_weapon_holder_instances().on_insert(...)`.
pub struct BackendWeaponHolderInstancesTableHandle<'ctx> {
    imp: __sdk::TableHandle<WeaponHolderInstance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_weapon_holder_instances`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendWeaponHolderInstancesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendWeaponHolderInstancesTableHandle`], which mediates access to the table `backend_weapon_holder_instances`.
    fn backend_weapon_holder_instances(&self) -> BackendWeaponHolderInstancesTableHandle<'_>;
}

impl BackendWeaponHolderInstancesTableAccess for super::RemoteTables {
    fn backend_weapon_holder_instances(&self) -> BackendWeaponHolderInstancesTableHandle<'_> {
        BackendWeaponHolderInstancesTableHandle {
            imp: self
                .imp
                .get_table::<WeaponHolderInstance>("backend_weapon_holder_instances"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendWeaponHolderInstancesInsertCallbackId(__sdk::CallbackId);
pub struct BackendWeaponHolderInstancesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendWeaponHolderInstancesTableHandle<'ctx> {
    type Row = WeaponHolderInstance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WeaponHolderInstance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendWeaponHolderInstancesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendWeaponHolderInstancesInsertCallbackId {
        BackendWeaponHolderInstancesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendWeaponHolderInstancesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendWeaponHolderInstancesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendWeaponHolderInstancesDeleteCallbackId {
        BackendWeaponHolderInstancesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendWeaponHolderInstancesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<WeaponHolderInstance>("backend_weapon_holder_instances");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WeaponHolderInstance>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WeaponHolderInstance>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WeaponHolderInstance`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_weapon_holder_instancesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WeaponHolderInstance`.
    fn backend_weapon_holder_instances(
        &self,
    ) -> __sdk::__query_builder::Table<WeaponHolderInstance>;
}

impl backend_weapon_holder_instancesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_weapon_holder_instances(
        &self,
    ) -> __sdk::__query_builder::Table<WeaponHolderInstance> {
        __sdk::__query_builder::Table::new("backend_weapon_holder_instances")
    }
}
