// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendInvestigationActionOutcome {
    pub owner_character_id: u64,
    pub outcome_id: String,
    pub action_id: String,
    pub wording: String,
    pub recorded_at: u64,
}

impl __sdk::InModule for BackendInvestigationActionOutcome {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendInvestigationActionOutcome`.
///
/// Provides typed access to columns for query building.
pub struct BackendInvestigationActionOutcomeCols {
    pub owner_character_id: __sdk::__query_builder::Col<BackendInvestigationActionOutcome, u64>,
    pub outcome_id: __sdk::__query_builder::Col<BackendInvestigationActionOutcome, String>,
    pub action_id: __sdk::__query_builder::Col<BackendInvestigationActionOutcome, String>,
    pub wording: __sdk::__query_builder::Col<BackendInvestigationActionOutcome, String>,
    pub recorded_at: __sdk::__query_builder::Col<BackendInvestigationActionOutcome, u64>,
}

impl __sdk::__query_builder::HasCols for BackendInvestigationActionOutcome {
    type Cols = BackendInvestigationActionOutcomeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendInvestigationActionOutcomeCols {
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            outcome_id: __sdk::__query_builder::Col::new(table_name, "outcome_id"),
            action_id: __sdk::__query_builder::Col::new(table_name, "action_id"),
            wording: __sdk::__query_builder::Col::new(table_name, "wording"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
        }
    }
}
