// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_npc_case_intervention_type::BackendNpcCaseIntervention;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_npc_case_interventions`.
///
/// Obtain a handle from the [`BackendNpcCaseInterventionsTableAccess::backend_npc_case_interventions`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_npc_case_interventions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_npc_case_interventions().on_insert(...)`.
pub struct BackendNpcCaseInterventionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendNpcCaseIntervention>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_npc_case_interventions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendNpcCaseInterventionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendNpcCaseInterventionsTableHandle`], which mediates access to the table `backend_npc_case_interventions`.
    fn backend_npc_case_interventions(&self) -> BackendNpcCaseInterventionsTableHandle<'_>;
}

impl BackendNpcCaseInterventionsTableAccess for super::RemoteTables {
    fn backend_npc_case_interventions(&self) -> BackendNpcCaseInterventionsTableHandle<'_> {
        BackendNpcCaseInterventionsTableHandle {
            imp: self
                .imp
                .get_table::<BackendNpcCaseIntervention>("backend_npc_case_interventions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendNpcCaseInterventionsInsertCallbackId(__sdk::CallbackId);
pub struct BackendNpcCaseInterventionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendNpcCaseInterventionsTableHandle<'ctx> {
    type Row = BackendNpcCaseIntervention;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendNpcCaseIntervention> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendNpcCaseInterventionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendNpcCaseInterventionsInsertCallbackId {
        BackendNpcCaseInterventionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendNpcCaseInterventionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendNpcCaseInterventionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendNpcCaseInterventionsDeleteCallbackId {
        BackendNpcCaseInterventionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendNpcCaseInterventionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<BackendNpcCaseIntervention>("backend_npc_case_interventions");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendNpcCaseIntervention>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendNpcCaseIntervention>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendNpcCaseIntervention`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_npc_case_interventionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendNpcCaseIntervention`.
    fn backend_npc_case_interventions(
        &self,
    ) -> __sdk::__query_builder::Table<BackendNpcCaseIntervention>;
}

impl backend_npc_case_interventionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_npc_case_interventions(
        &self,
    ) -> __sdk::__query_builder::Table<BackendNpcCaseIntervention> {
        __sdk::__query_builder::Table::new("backend_npc_case_interventions")
    }
}
