// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_browser_character_access_type::BackendBrowserCharacterAccess;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_browser_character_access`.
///
/// Obtain a handle from the [`BackendBrowserCharacterAccessTableAccess::backend_browser_character_access`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_browser_character_access()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_browser_character_access().on_insert(...)`.
pub struct BackendBrowserCharacterAccessTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendBrowserCharacterAccess>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_browser_character_access`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendBrowserCharacterAccessTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendBrowserCharacterAccessTableHandle`], which mediates access to the table `backend_browser_character_access`.
    fn backend_browser_character_access(&self) -> BackendBrowserCharacterAccessTableHandle<'_>;
}

impl BackendBrowserCharacterAccessTableAccess for super::RemoteTables {
    fn backend_browser_character_access(&self) -> BackendBrowserCharacterAccessTableHandle<'_> {
        BackendBrowserCharacterAccessTableHandle {
            imp: self
                .imp
                .get_table::<BackendBrowserCharacterAccess>("backend_browser_character_access"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendBrowserCharacterAccessInsertCallbackId(__sdk::CallbackId);
pub struct BackendBrowserCharacterAccessDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendBrowserCharacterAccessTableHandle<'ctx> {
    type Row = BackendBrowserCharacterAccess;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendBrowserCharacterAccess> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendBrowserCharacterAccessInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendBrowserCharacterAccessInsertCallbackId {
        BackendBrowserCharacterAccessInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendBrowserCharacterAccessInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendBrowserCharacterAccessDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendBrowserCharacterAccessDeleteCallbackId {
        BackendBrowserCharacterAccessDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendBrowserCharacterAccessDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<BackendBrowserCharacterAccess>("backend_browser_character_access");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendBrowserCharacterAccess>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<BackendBrowserCharacterAccess>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendBrowserCharacterAccess`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_browser_character_accessQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendBrowserCharacterAccess`.
    fn backend_browser_character_access(
        &self,
    ) -> __sdk::__query_builder::Table<BackendBrowserCharacterAccess>;
}

impl backend_browser_character_accessQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_browser_character_access(
        &self,
    ) -> __sdk::__query_builder::Table<BackendBrowserCharacterAccess> {
        __sdk::__query_builder::Table::new("backend_browser_character_access")
    }
}
