// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::backend_forage_attempt_state_type::BackendForageAttemptState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_forage_attempt_states`.
///
/// Obtain a handle from the [`BackendForageAttemptStatesTableAccess::backend_forage_attempt_states`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_forage_attempt_states()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_forage_attempt_states().on_insert(...)`.
pub struct BackendForageAttemptStatesTableHandle<'ctx> {
    imp: __sdk::TableHandle<BackendForageAttemptState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_forage_attempt_states`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendForageAttemptStatesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendForageAttemptStatesTableHandle`], which mediates access to the table `backend_forage_attempt_states`.
    fn backend_forage_attempt_states(&self) -> BackendForageAttemptStatesTableHandle<'_>;
}

impl BackendForageAttemptStatesTableAccess for super::RemoteTables {
    fn backend_forage_attempt_states(&self) -> BackendForageAttemptStatesTableHandle<'_> {
        BackendForageAttemptStatesTableHandle {
            imp: self
                .imp
                .get_table::<BackendForageAttemptState>("backend_forage_attempt_states"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendForageAttemptStatesInsertCallbackId(__sdk::CallbackId);
pub struct BackendForageAttemptStatesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendForageAttemptStatesTableHandle<'ctx> {
    type Row = BackendForageAttemptState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BackendForageAttemptState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendForageAttemptStatesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendForageAttemptStatesInsertCallbackId {
        BackendForageAttemptStatesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendForageAttemptStatesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendForageAttemptStatesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendForageAttemptStatesDeleteCallbackId {
        BackendForageAttemptStatesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendForageAttemptStatesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<BackendForageAttemptState>("backend_forage_attempt_states");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BackendForageAttemptState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BackendForageAttemptState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BackendForageAttemptState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_forage_attempt_statesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BackendForageAttemptState`.
    fn backend_forage_attempt_states(
        &self,
    ) -> __sdk::__query_builder::Table<BackendForageAttemptState>;
}

impl backend_forage_attempt_statesQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_forage_attempt_states(
        &self,
    ) -> __sdk::__query_builder::Table<BackendForageAttemptState> {
        __sdk::__query_builder::Table::new("backend_forage_attempt_states")
    }
}
