// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_limbs_type::CharacterLimbs;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_character_limbs`.
///
/// Obtain a handle from the [`BackendCharacterLimbsTableAccess::backend_character_limbs`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_character_limbs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_character_limbs().on_insert(...)`.
pub struct BackendCharacterLimbsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterLimbs>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_character_limbs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendCharacterLimbsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendCharacterLimbsTableHandle`], which mediates access to the table `backend_character_limbs`.
    fn backend_character_limbs(&self) -> BackendCharacterLimbsTableHandle<'_>;
}

impl BackendCharacterLimbsTableAccess for super::RemoteTables {
    fn backend_character_limbs(&self) -> BackendCharacterLimbsTableHandle<'_> {
        BackendCharacterLimbsTableHandle {
            imp: self
                .imp
                .get_table::<CharacterLimbs>("backend_character_limbs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendCharacterLimbsInsertCallbackId(__sdk::CallbackId);
pub struct BackendCharacterLimbsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendCharacterLimbsTableHandle<'ctx> {
    type Row = CharacterLimbs;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterLimbs> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendCharacterLimbsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterLimbsInsertCallbackId {
        BackendCharacterLimbsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendCharacterLimbsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendCharacterLimbsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendCharacterLimbsDeleteCallbackId {
        BackendCharacterLimbsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendCharacterLimbsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterLimbs>("backend_character_limbs");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterLimbs>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterLimbs>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterLimbs`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_character_limbsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterLimbs`.
    fn backend_character_limbs(&self) -> __sdk::__query_builder::Table<CharacterLimbs>;
}

impl backend_character_limbsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_character_limbs(&self) -> __sdk::__query_builder::Table<CharacterLimbs> {
        __sdk::__query_builder::Table::new("backend_character_limbs")
    }
}
