// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendDialogueWitnessClaim {
    pub observer_character_id: u64,
    pub session_id: String,
    pub npc_id: String,
    pub event_sequence: u32,
    pub claim_order: u32,
    pub challenge_token: String,
    pub displayed_text: String,
    pub assessment_direction: String,
    pub assessment_strength: f32,
    pub resolved: bool,
    pub outcome: String,
    pub affinity_delta: f32,
}

impl __sdk::InModule for BackendDialogueWitnessClaim {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendDialogueWitnessClaim`.
///
/// Provides typed access to columns for query building.
pub struct BackendDialogueWitnessClaimCols {
    pub observer_character_id: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, u64>,
    pub session_id: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub npc_id: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub event_sequence: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, u32>,
    pub claim_order: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, u32>,
    pub challenge_token: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub displayed_text: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub assessment_direction: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub assessment_strength: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, f32>,
    pub resolved: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, bool>,
    pub outcome: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, String>,
    pub affinity_delta: __sdk::__query_builder::Col<BackendDialogueWitnessClaim, f32>,
}

impl __sdk::__query_builder::HasCols for BackendDialogueWitnessClaim {
    type Cols = BackendDialogueWitnessClaimCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendDialogueWitnessClaimCols {
            observer_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "observer_character_id",
            ),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            event_sequence: __sdk::__query_builder::Col::new(table_name, "event_sequence"),
            claim_order: __sdk::__query_builder::Col::new(table_name, "claim_order"),
            challenge_token: __sdk::__query_builder::Col::new(table_name, "challenge_token"),
            displayed_text: __sdk::__query_builder::Col::new(table_name, "displayed_text"),
            assessment_direction: __sdk::__query_builder::Col::new(
                table_name,
                "assessment_direction",
            ),
            assessment_strength: __sdk::__query_builder::Col::new(
                table_name,
                "assessment_strength",
            ),
            resolved: __sdk::__query_builder::Col::new(table_name, "resolved"),
            outcome: __sdk::__query_builder::Col::new(table_name, "outcome"),
            affinity_delta: __sdk::__query_builder::Col::new(table_name, "affinity_delta"),
        }
    }
}
