// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendForageReceipt {
    pub character_id: u64,
    pub request_id: String,
    pub elapsed_minutes: u64,
    pub yielded_item_ids: Vec::<String>,
    pub yielded_quantities: Vec::<u16>,
    pub interrupted: bool,
    pub legal_outcome: String,
}


impl __sdk::InModule for BackendForageReceipt {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `BackendForageReceipt`.
///
/// Provides typed access to columns for query building.
pub struct BackendForageReceiptCols {
    pub character_id: __sdk::__query_builder::Col<BackendForageReceipt, u64>,
    pub request_id: __sdk::__query_builder::Col<BackendForageReceipt, String>,
    pub elapsed_minutes: __sdk::__query_builder::Col<BackendForageReceipt, u64>,
    pub yielded_item_ids: __sdk::__query_builder::Col<BackendForageReceipt, Vec::<String>>,
    pub yielded_quantities: __sdk::__query_builder::Col<BackendForageReceipt, Vec::<u16>>,
    pub interrupted: __sdk::__query_builder::Col<BackendForageReceipt, bool>,
    pub legal_outcome: __sdk::__query_builder::Col<BackendForageReceipt, String>,
}

impl __sdk::__query_builder::HasCols for BackendForageReceipt {
    type Cols = BackendForageReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendForageReceiptCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            elapsed_minutes: __sdk::__query_builder::Col::new(table_name, "elapsed_minutes"),
            yielded_item_ids: __sdk::__query_builder::Col::new(table_name, "yielded_item_ids"),
            yielded_quantities: __sdk::__query_builder::Col::new(table_name, "yielded_quantities"),
            interrupted: __sdk::__query_builder::Col::new(table_name, "interrupted"),
            legal_outcome: __sdk::__query_builder::Col::new(table_name, "legal_outcome"),

        }
    }
}

