// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendLocalProblemTradeEffect {
    pub character_id: u64,
    pub settlement_id: String,
    pub buy_bps: i32,
    pub sell_penalty_bps: i32,
}


impl __sdk::InModule for BackendLocalProblemTradeEffect {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `BackendLocalProblemTradeEffect`.
///
/// Provides typed access to columns for query building.
pub struct BackendLocalProblemTradeEffectCols {
    pub character_id: __sdk::__query_builder::Col<BackendLocalProblemTradeEffect, u64>,
    pub settlement_id: __sdk::__query_builder::Col<BackendLocalProblemTradeEffect, String>,
    pub buy_bps: __sdk::__query_builder::Col<BackendLocalProblemTradeEffect, i32>,
    pub sell_penalty_bps: __sdk::__query_builder::Col<BackendLocalProblemTradeEffect, i32>,
}

impl __sdk::__query_builder::HasCols for BackendLocalProblemTradeEffect {
    type Cols = BackendLocalProblemTradeEffectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendLocalProblemTradeEffectCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            buy_bps: __sdk::__query_builder::Col::new(table_name, "buy_bps"),
            sell_penalty_bps: __sdk::__query_builder::Col::new(table_name, "sell_penalty_bps"),

        }
    }
}

