// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendLocalProblemRumor {
    pub receipt_id: String,
    pub character_id: u64,
    pub settlement_id: String,
    pub session_id: String,
    pub delivery_text: String,
}

impl __sdk::InModule for BackendLocalProblemRumor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendLocalProblemRumor`.
///
/// Provides typed access to columns for query building.
pub struct BackendLocalProblemRumorCols {
    pub receipt_id: __sdk::__query_builder::Col<BackendLocalProblemRumor, String>,
    pub character_id: __sdk::__query_builder::Col<BackendLocalProblemRumor, u64>,
    pub settlement_id: __sdk::__query_builder::Col<BackendLocalProblemRumor, String>,
    pub session_id: __sdk::__query_builder::Col<BackendLocalProblemRumor, String>,
    pub delivery_text: __sdk::__query_builder::Col<BackendLocalProblemRumor, String>,
}

impl __sdk::__query_builder::HasCols for BackendLocalProblemRumor {
    type Cols = BackendLocalProblemRumorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendLocalProblemRumorCols {
            receipt_id: __sdk::__query_builder::Col::new(table_name, "receipt_id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            delivery_text: __sdk::__query_builder::Col::new(table_name, "delivery_text"),
        }
    }
}
