// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::automatic_social_chat_type::AutomaticSocialChat;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `backend_automatic_social_chats`.
///
/// Obtain a handle from the [`BackendAutomaticSocialChatsTableAccess::backend_automatic_social_chats`] method on [`super::RemoteTables`],
/// like `ctx.db.backend_automatic_social_chats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.backend_automatic_social_chats().on_insert(...)`.
pub struct BackendAutomaticSocialChatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AutomaticSocialChat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `backend_automatic_social_chats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BackendAutomaticSocialChatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BackendAutomaticSocialChatsTableHandle`], which mediates access to the table `backend_automatic_social_chats`.
    fn backend_automatic_social_chats(&self) -> BackendAutomaticSocialChatsTableHandle<'_>;
}

impl BackendAutomaticSocialChatsTableAccess for super::RemoteTables {
    fn backend_automatic_social_chats(&self) -> BackendAutomaticSocialChatsTableHandle<'_> {
        BackendAutomaticSocialChatsTableHandle {
            imp: self
                .imp
                .get_table::<AutomaticSocialChat>("backend_automatic_social_chats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BackendAutomaticSocialChatsInsertCallbackId(__sdk::CallbackId);
pub struct BackendAutomaticSocialChatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BackendAutomaticSocialChatsTableHandle<'ctx> {
    type Row = AutomaticSocialChat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AutomaticSocialChat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BackendAutomaticSocialChatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendAutomaticSocialChatsInsertCallbackId {
        BackendAutomaticSocialChatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BackendAutomaticSocialChatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BackendAutomaticSocialChatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BackendAutomaticSocialChatsDeleteCallbackId {
        BackendAutomaticSocialChatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BackendAutomaticSocialChatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<AutomaticSocialChat>("backend_automatic_social_chats");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AutomaticSocialChat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AutomaticSocialChat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AutomaticSocialChat`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait backend_automatic_social_chatsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AutomaticSocialChat`.
    fn backend_automatic_social_chats(&self) -> __sdk::__query_builder::Table<AutomaticSocialChat>;
}

impl backend_automatic_social_chatsQueryTableAccess for __sdk::QueryTableAccessor {
    fn backend_automatic_social_chats(&self) -> __sdk::__query_builder::Table<AutomaticSocialChat> {
        __sdk::__query_builder::Table::new("backend_automatic_social_chats")
    }
}
