// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::case_site_id_type::CaseSiteId;
use super::challenge_presenter_catalog_id_type::ChallengePresenterCatalogId;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BackendChallenge {
    pub id: String,
    pub case_id: String,
    pub party_id: String,
    pub owner_character_id: u64,
    pub finale_case_site_id: CaseSiteId,
    pub puzzle_projection_json: String,
    pub presenter_catalog_id: ChallengePresenterCatalogId,
    pub revision: u32,
    pub open: bool,
    pub solved: bool,
    pub active: bool,
    pub last_attempt_correct: Option<bool>,
    pub last_submission_json: Option<String>,
    pub tactical_insight_text: Option<String>,
    pub tactical_preparation_text: Option<String>,
}

impl __sdk::InModule for BackendChallenge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BackendChallenge`.
///
/// Provides typed access to columns for query building.
pub struct BackendChallengeCols {
    pub id: __sdk::__query_builder::Col<BackendChallenge, String>,
    pub case_id: __sdk::__query_builder::Col<BackendChallenge, String>,
    pub party_id: __sdk::__query_builder::Col<BackendChallenge, String>,
    pub owner_character_id: __sdk::__query_builder::Col<BackendChallenge, u64>,
    pub finale_case_site_id: __sdk::__query_builder::Col<BackendChallenge, CaseSiteId>,
    pub puzzle_projection_json: __sdk::__query_builder::Col<BackendChallenge, String>,
    pub presenter_catalog_id:
        __sdk::__query_builder::Col<BackendChallenge, ChallengePresenterCatalogId>,
    pub revision: __sdk::__query_builder::Col<BackendChallenge, u32>,
    pub open: __sdk::__query_builder::Col<BackendChallenge, bool>,
    pub solved: __sdk::__query_builder::Col<BackendChallenge, bool>,
    pub active: __sdk::__query_builder::Col<BackendChallenge, bool>,
    pub last_attempt_correct: __sdk::__query_builder::Col<BackendChallenge, Option<bool>>,
    pub last_submission_json: __sdk::__query_builder::Col<BackendChallenge, Option<String>>,
    pub tactical_insight_text: __sdk::__query_builder::Col<BackendChallenge, Option<String>>,
    pub tactical_preparation_text: __sdk::__query_builder::Col<BackendChallenge, Option<String>>,
}

impl __sdk::__query_builder::HasCols for BackendChallenge {
    type Cols = BackendChallengeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BackendChallengeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            finale_case_site_id: __sdk::__query_builder::Col::new(
                table_name,
                "finale_case_site_id",
            ),
            puzzle_projection_json: __sdk::__query_builder::Col::new(
                table_name,
                "puzzle_projection_json",
            ),
            presenter_catalog_id: __sdk::__query_builder::Col::new(
                table_name,
                "presenter_catalog_id",
            ),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            open: __sdk::__query_builder::Col::new(table_name, "open"),
            solved: __sdk::__query_builder::Col::new(table_name, "solved"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            last_attempt_correct: __sdk::__query_builder::Col::new(
                table_name,
                "last_attempt_correct",
            ),
            last_submission_json: __sdk::__query_builder::Col::new(
                table_name,
                "last_submission_json",
            ),
            tactical_insight_text: __sdk::__query_builder::Col::new(
                table_name,
                "tactical_insight_text",
            ),
            tactical_preparation_text: __sdk::__query_builder::Col::new(
                table_name,
                "tactical_preparation_text",
            ),
        }
    }
}
