// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BurnCorpseArgs {
    pub actor_id: u64,
    pub corpse_id: String,
    pub action_id: String,
    pub expected_revision: u32,
    pub confirm_destruction: bool,
}

impl From<BurnCorpseArgs> for super::Reducer {
    fn from(args: BurnCorpseArgs) -> Self {
        Self::BurnCorpse {
            actor_id: args.actor_id,
            corpse_id: args.corpse_id,
            action_id: args.action_id,
            expected_revision: args.expected_revision,
            confirm_destruction: args.confirm_destruction,
        }
    }
}

impl __sdk::InModule for BurnCorpseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `burn_corpse`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait burn_corpse {
    /// Request that the remote module invoke the reducer `burn_corpse` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`burn_corpse:burn_corpse_then`] to run a callback after the reducer completes.
    fn burn_corpse(
        &self,
        actor_id: u64,
        corpse_id: String,
        action_id: String,
        expected_revision: u32,
        confirm_destruction: bool,
    ) -> __sdk::Result<()> {
        self.burn_corpse_then(
            actor_id,
            corpse_id,
            action_id,
            expected_revision,
            confirm_destruction,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `burn_corpse` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn burn_corpse_then(
        &self,
        actor_id: u64,
        corpse_id: String,
        action_id: String,
        expected_revision: u32,
        confirm_destruction: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl burn_corpse for super::RemoteReducers {
    fn burn_corpse_then(
        &self,
        actor_id: u64,
        corpse_id: String,
        action_id: String,
        expected_revision: u32,
        confirm_destruction: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BurnCorpseArgs {
                actor_id,
                corpse_id,
                action_id,
                expected_revision,
                confirm_destruction,
            },
            callback,
        )
    }
}
