// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChangeInventoryItemArgs {
    pub character_id: u64,
    pub item_id: String,
    pub by_quantity: i32,
}

impl From<ChangeInventoryItemArgs> for super::Reducer {
    fn from(args: ChangeInventoryItemArgs) -> Self {
        Self::ChangeInventoryItem {
            character_id: args.character_id,
            item_id: args.item_id,
            by_quantity: args.by_quantity,
}
}
}

impl __sdk::InModule for ChangeInventoryItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `change_inventory_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait change_inventory_item {
    /// Request that the remote module invoke the reducer `change_inventory_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`change_inventory_item:change_inventory_item_then`] to run a callback after the reducer completes.
    fn change_inventory_item(&self, character_id: u64,
item_id: String,
by_quantity: i32,
) -> __sdk::Result<()> {
        self.change_inventory_item_then(character_id, item_id, by_quantity,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `change_inventory_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn change_inventory_item_then(
        &self,
        character_id: u64,
item_id: String,
by_quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl change_inventory_item for super::RemoteReducers {
    fn change_inventory_item_then(
        &self,
        character_id: u64,
item_id: String,
by_quantity: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ChangeInventoryItemArgs { character_id, item_id, by_quantity,  }, callback)
    }
}

