// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::nerve_type::Nerve;
use super::drive_type::Drive;
use super::outlook_type::Outlook;
use super::sociability_type::Sociability;
use super::conscience_type::Conscience;
use super::self_regard_type::SelfRegard;
use super::conviction_type::Conviction;
use super::hygiene_type::Hygiene;
use super::temperance_type::Temperance;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterPersonality {
    pub character_id: u64,
    pub nerve: Nerve,
    pub drive: Drive,
    pub outlook: Outlook,
    pub sociability: Sociability,
    pub conscience: Conscience,
    pub self_regard: SelfRegard,
    pub conviction: Conviction,
    pub hygiene: Hygiene,
    pub temperance: Temperance,
}


impl __sdk::InModule for CharacterPersonality {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `CharacterPersonality`.
///
/// Provides typed access to columns for query building.
pub struct CharacterPersonalityCols {
    pub character_id: __sdk::__query_builder::Col<CharacterPersonality, u64>,
    pub nerve: __sdk::__query_builder::Col<CharacterPersonality, Nerve>,
    pub drive: __sdk::__query_builder::Col<CharacterPersonality, Drive>,
    pub outlook: __sdk::__query_builder::Col<CharacterPersonality, Outlook>,
    pub sociability: __sdk::__query_builder::Col<CharacterPersonality, Sociability>,
    pub conscience: __sdk::__query_builder::Col<CharacterPersonality, Conscience>,
    pub self_regard: __sdk::__query_builder::Col<CharacterPersonality, SelfRegard>,
    pub conviction: __sdk::__query_builder::Col<CharacterPersonality, Conviction>,
    pub hygiene: __sdk::__query_builder::Col<CharacterPersonality, Hygiene>,
    pub temperance: __sdk::__query_builder::Col<CharacterPersonality, Temperance>,
}

impl __sdk::__query_builder::HasCols for CharacterPersonality {
    type Cols = CharacterPersonalityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterPersonalityCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            nerve: __sdk::__query_builder::Col::new(table_name, "nerve"),
            drive: __sdk::__query_builder::Col::new(table_name, "drive"),
            outlook: __sdk::__query_builder::Col::new(table_name, "outlook"),
            sociability: __sdk::__query_builder::Col::new(table_name, "sociability"),
            conscience: __sdk::__query_builder::Col::new(table_name, "conscience"),
            self_regard: __sdk::__query_builder::Col::new(table_name, "self_regard"),
            conviction: __sdk::__query_builder::Col::new(table_name, "conviction"),
            hygiene: __sdk::__query_builder::Col::new(table_name, "hygiene"),
            temperance: __sdk::__query_builder::Col::new(table_name, "temperance"),

        }
    }
}

/// Indexed column accessor struct for the table `CharacterPersonality`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterPersonalityIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterPersonality, u64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterPersonality {
    type IxCols = CharacterPersonalityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterPersonalityIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterPersonality {}

