// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_familiarity_type::CharacterFamiliarity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_familiarity`.
///
/// Obtain a handle from the [`CharacterFamiliarityTableAccess::character_familiarity`] method on [`super::RemoteTables`],
/// like `ctx.db.character_familiarity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_familiarity().on_insert(...)`.
pub struct CharacterFamiliarityTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterFamiliarity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_familiarity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterFamiliarityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterFamiliarityTableHandle`], which mediates access to the table `character_familiarity`.
    fn character_familiarity(&self) -> CharacterFamiliarityTableHandle<'_>;
}

impl CharacterFamiliarityTableAccess for super::RemoteTables {
    fn character_familiarity(&self) -> CharacterFamiliarityTableHandle<'_> {
        CharacterFamiliarityTableHandle {
            imp: self
                .imp
                .get_table::<CharacterFamiliarity>("character_familiarity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterFamiliarityInsertCallbackId(__sdk::CallbackId);
pub struct CharacterFamiliarityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterFamiliarityTableHandle<'ctx> {
    type Row = CharacterFamiliarity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterFamiliarity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterFamiliarityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterFamiliarityInsertCallbackId {
        CharacterFamiliarityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterFamiliarityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterFamiliarityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterFamiliarityDeleteCallbackId {
        CharacterFamiliarityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterFamiliarityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CharacterFamiliarityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterFamiliarityTableHandle<'ctx> {
    type UpdateCallbackId = CharacterFamiliarityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterFamiliarityUpdateCallbackId {
        CharacterFamiliarityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterFamiliarityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `character_familiarity`,
/// which allows point queries on the field of the same name
/// via the [`CharacterFamiliarityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_familiarity().id().find(...)`.
pub struct CharacterFamiliarityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterFamiliarity, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterFamiliarityTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `character_familiarity`.
    pub fn id(&self) -> CharacterFamiliarityIdUnique<'ctx> {
        CharacterFamiliarityIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterFamiliarityIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CharacterFamiliarity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterFamiliarity>("character_familiarity");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CharacterFamiliarity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterFamiliarity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CharacterFamiliarity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait character_familiarityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CharacterFamiliarity`.
    fn character_familiarity(&self) -> __sdk::__query_builder::Table<CharacterFamiliarity>;
}

impl character_familiarityQueryTableAccess for __sdk::QueryTableAccessor {
    fn character_familiarity(&self) -> __sdk::__query_builder::Table<CharacterFamiliarity> {
        __sdk::__query_builder::Table::new("character_familiarity")
    }
}
