// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterExposure {
    pub character_id: u64,
    pub wetness_bps: u16,
    pub thermal_strain: i32,
    pub frostbite_progress_minutes: u32,
}

impl __sdk::InModule for CharacterExposure {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CharacterExposure`.
///
/// Provides typed access to columns for query building.
pub struct CharacterExposureCols {
    pub character_id: __sdk::__query_builder::Col<CharacterExposure, u64>,
    pub wetness_bps: __sdk::__query_builder::Col<CharacterExposure, u16>,
    pub thermal_strain: __sdk::__query_builder::Col<CharacterExposure, i32>,
    pub frostbite_progress_minutes: __sdk::__query_builder::Col<CharacterExposure, u32>,
}

impl __sdk::__query_builder::HasCols for CharacterExposure {
    type Cols = CharacterExposureCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterExposureCols {
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            wetness_bps: __sdk::__query_builder::Col::new(table_name, "wetness_bps"),
            thermal_strain: __sdk::__query_builder::Col::new(table_name, "thermal_strain"),
            frostbite_progress_minutes: __sdk::__query_builder::Col::new(
                table_name,
                "frostbite_progress_minutes",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `CharacterExposure`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterExposureIxCols {
    pub character_id: __sdk::__query_builder::IxCol<CharacterExposure, u64>,
}

impl __sdk::__query_builder::HasIxCols for CharacterExposure {
    type IxCols = CharacterExposureIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterExposureIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CharacterExposure {}
