// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::character_attributes_type::CharacterAttributes;
use super::character_skills_type::CharacterSkills;
use super::schedule_allocation_type::ScheduleAllocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConfigureSimulationCharacterArgs {
    pub nonce: String,
    pub character_id: u64,
    pub agent_id: u32,
    pub settlement_id: String,
    pub attributes: CharacterAttributes,
    pub skills: CharacterSkills,
    pub downtime: ScheduleAllocation,
}

impl From<ConfigureSimulationCharacterArgs> for super::Reducer {
    fn from(args: ConfigureSimulationCharacterArgs) -> Self {
        Self::ConfigureSimulationCharacter {
            nonce: args.nonce,
            character_id: args.character_id,
            agent_id: args.agent_id,
            settlement_id: args.settlement_id,
            attributes: args.attributes,
            skills: args.skills,
            downtime: args.downtime,
        }
    }
}

impl __sdk::InModule for ConfigureSimulationCharacterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `configure_simulation_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait configure_simulation_character {
    /// Request that the remote module invoke the reducer `configure_simulation_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`configure_simulation_character:configure_simulation_character_then`] to run a callback after the reducer completes.
    fn configure_simulation_character(
        &self,
        nonce: String,
        character_id: u64,
        agent_id: u32,
        settlement_id: String,
        attributes: CharacterAttributes,
        skills: CharacterSkills,
        downtime: ScheduleAllocation,
    ) -> __sdk::Result<()> {
        self.configure_simulation_character_then(
            nonce,
            character_id,
            agent_id,
            settlement_id,
            attributes,
            skills,
            downtime,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `configure_simulation_character` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn configure_simulation_character_then(
        &self,
        nonce: String,
        character_id: u64,
        agent_id: u32,
        settlement_id: String,
        attributes: CharacterAttributes,
        skills: CharacterSkills,
        downtime: ScheduleAllocation,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl configure_simulation_character for super::RemoteReducers {
    fn configure_simulation_character_then(
        &self,
        nonce: String,
        character_id: u64,
        agent_id: u32,
        settlement_id: String,
        attributes: CharacterAttributes,
        skills: CharacterSkills,
        downtime: ScheduleAllocation,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ConfigureSimulationCharacterArgs {
                nonce,
                character_id,
                agent_id,
                settlement_id,
                attributes,
                skills,
                downtime,
            },
            callback,
        )
    }
}
