// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_attributes_type::CharacterAttributes;
use super::character_limbs_type::CharacterLimbs;
use super::character_skills_type::CharacterSkills;
use super::character_stats_type::CharacterStats;
use super::character_type::Character;
use super::connected_player_item_type::ConnectedPlayerItem;
use super::connected_player_type::ConnectedPlayer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `connected_players`.
///
/// Obtain a handle from the [`ConnectedPlayersTableAccess::connected_players`] method on [`super::RemoteTables`],
/// like `ctx.db.connected_players()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.connected_players().on_insert(...)`.
pub struct ConnectedPlayersTableHandle<'ctx> {
    imp: __sdk::TableHandle<ConnectedPlayer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `connected_players`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConnectedPlayersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConnectedPlayersTableHandle`], which mediates access to the table `connected_players`.
    fn connected_players(&self) -> ConnectedPlayersTableHandle<'_>;
}

impl ConnectedPlayersTableAccess for super::RemoteTables {
    fn connected_players(&self) -> ConnectedPlayersTableHandle<'_> {
        ConnectedPlayersTableHandle {
            imp: self.imp.get_table::<ConnectedPlayer>("connected_players"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConnectedPlayersInsertCallbackId(__sdk::CallbackId);
pub struct ConnectedPlayersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConnectedPlayersTableHandle<'ctx> {
    type Row = ConnectedPlayer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ConnectedPlayer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConnectedPlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectedPlayersInsertCallbackId {
        ConnectedPlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConnectedPlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConnectedPlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectedPlayersDeleteCallbackId {
        ConnectedPlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConnectedPlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ConnectedPlayer>("connected_players");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ConnectedPlayer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ConnectedPlayer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
