// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::production_scale_type::ProductionScale;
use super::construction_commodity_type::ConstructionCommodity;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ConstructionIndustry {
    pub commodity: ConstructionCommodity,
    pub scale: ProductionScale,
}


impl __sdk::InModule for ConstructionIndustry {
    type Module = super::RemoteModule;
}

