// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::contract_status_type::ContractStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Contract {
    pub id: String,
    pub gateway_bucket: u8,
    pub case_id: String,
    pub title: String,
    pub description: String,
    pub difficulty: i32,
    pub gold_reward: i32,
    pub xp_reward: i32,
    pub settlement_id: String,
    pub service_id: String,
    pub issuer_resident_character_id: u64,
    pub status: ContractStatus,
    pub accepted_by: Option<String>,
    pub opposition_wording: String,
    pub opposition_count_wording: String,
    pub accepted_at_minute: Option<u64>,
    pub paid_at_minute: Option<u64>,
}

impl __sdk::InModule for Contract {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Contract`.
///
/// Provides typed access to columns for query building.
pub struct ContractCols {
    pub id: __sdk::__query_builder::Col<Contract, String>,
    pub gateway_bucket: __sdk::__query_builder::Col<Contract, u8>,
    pub case_id: __sdk::__query_builder::Col<Contract, String>,
    pub title: __sdk::__query_builder::Col<Contract, String>,
    pub description: __sdk::__query_builder::Col<Contract, String>,
    pub difficulty: __sdk::__query_builder::Col<Contract, i32>,
    pub gold_reward: __sdk::__query_builder::Col<Contract, i32>,
    pub xp_reward: __sdk::__query_builder::Col<Contract, i32>,
    pub settlement_id: __sdk::__query_builder::Col<Contract, String>,
    pub service_id: __sdk::__query_builder::Col<Contract, String>,
    pub issuer_resident_character_id: __sdk::__query_builder::Col<Contract, u64>,
    pub status: __sdk::__query_builder::Col<Contract, ContractStatus>,
    pub accepted_by: __sdk::__query_builder::Col<Contract, Option<String>>,
    pub opposition_wording: __sdk::__query_builder::Col<Contract, String>,
    pub opposition_count_wording: __sdk::__query_builder::Col<Contract, String>,
    pub accepted_at_minute: __sdk::__query_builder::Col<Contract, Option<u64>>,
    pub paid_at_minute: __sdk::__query_builder::Col<Contract, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for Contract {
    type Cols = ContractCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContractCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            gateway_bucket: __sdk::__query_builder::Col::new(table_name, "gateway_bucket"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            difficulty: __sdk::__query_builder::Col::new(table_name, "difficulty"),
            gold_reward: __sdk::__query_builder::Col::new(table_name, "gold_reward"),
            xp_reward: __sdk::__query_builder::Col::new(table_name, "xp_reward"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            service_id: __sdk::__query_builder::Col::new(table_name, "service_id"),
            issuer_resident_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "issuer_resident_character_id",
            ),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            accepted_by: __sdk::__query_builder::Col::new(table_name, "accepted_by"),
            opposition_wording: __sdk::__query_builder::Col::new(table_name, "opposition_wording"),
            opposition_count_wording: __sdk::__query_builder::Col::new(
                table_name,
                "opposition_count_wording",
            ),
            accepted_at_minute: __sdk::__query_builder::Col::new(table_name, "accepted_at_minute"),
            paid_at_minute: __sdk::__query_builder::Col::new(table_name, "paid_at_minute"),
        }
    }
}

/// Indexed column accessor struct for the table `Contract`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContractIxCols {
    pub case_id: __sdk::__query_builder::IxCol<Contract, String>,
    pub gateway_bucket: __sdk::__query_builder::IxCol<Contract, u8>,
    pub id: __sdk::__query_builder::IxCol<Contract, String>,
    pub service_id: __sdk::__query_builder::IxCol<Contract, String>,
    pub settlement_id: __sdk::__query_builder::IxCol<Contract, String>,
}

impl __sdk::__query_builder::HasIxCols for Contract {
    type IxCols = ContractIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContractIxCols {
            case_id: __sdk::__query_builder::IxCol::new(table_name, "case_id"),
            gateway_bucket: __sdk::__query_builder::IxCol::new(table_name, "gateway_bucket"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            service_id: __sdk::__query_builder::IxCol::new(table_name, "service_id"),
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Contract {}
