// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::recruitment_requirements_type::RecruitmentRequirements;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateRecruitmentRoleArgs {
    pub leader_id: u64,
    pub name: String,
    pub quantity: u32,
    pub requirements: RecruitmentRequirements,
    pub weapon_precision: f32,
    pub save_role: bool,
}

impl From<CreateRecruitmentRoleArgs> for super::Reducer {
    fn from(args: CreateRecruitmentRoleArgs) -> Self {
        Self::CreateRecruitmentRole {
            leader_id: args.leader_id,
            name: args.name,
            quantity: args.quantity,
            requirements: args.requirements,
            weapon_precision: args.weapon_precision,
            save_role: args.save_role,
}
}
}

impl __sdk::InModule for CreateRecruitmentRoleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_recruitment_role`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_recruitment_role {
    /// Request that the remote module invoke the reducer `create_recruitment_role` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_recruitment_role:create_recruitment_role_then`] to run a callback after the reducer completes.
    fn create_recruitment_role(&self, leader_id: u64,
name: String,
quantity: u32,
requirements: RecruitmentRequirements,
weapon_precision: f32,
save_role: bool,
) -> __sdk::Result<()> {
        self.create_recruitment_role_then(leader_id, name, quantity, requirements, weapon_precision, save_role,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_recruitment_role` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_recruitment_role_then(
        &self,
        leader_id: u64,
name: String,
quantity: u32,
requirements: RecruitmentRequirements,
weapon_precision: f32,
save_role: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_recruitment_role for super::RemoteReducers {
    fn create_recruitment_role_then(
        &self,
        leader_id: u64,
name: String,
quantity: u32,
requirements: RecruitmentRequirements,
weapon_precision: f32,
save_role: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CreateRecruitmentRoleArgs { leader_id, name, quantity, requirements, weapon_precision, save_role,  }, callback)
    }
}

