// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::starting_age_tier_coordinate_type::StartingAgeTierCoordinate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateStartingCharacterArgs {
    pub owner_key: String,
    pub generator_version: u16,
    pub seed: String,
    pub age_tier: StartingAgeTierCoordinate,
    pub slot: u8,
}

impl From<CreateStartingCharacterArgs> for super::Reducer {
    fn from(args: CreateStartingCharacterArgs) -> Self {
        Self::CreateStartingCharacter {
            owner_key: args.owner_key,
            generator_version: args.generator_version,
            seed: args.seed,
            age_tier: args.age_tier,
            slot: args.slot,
        }
    }
}

impl __sdk::InModule for CreateStartingCharacterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_starting_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_starting_character {
    /// Request that the remote module invoke the reducer `create_starting_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_starting_character:create_starting_character_then`] to run a callback after the reducer completes.
    fn create_starting_character(
        &self,
        owner_key: String,
        generator_version: u16,
        seed: String,
        age_tier: StartingAgeTierCoordinate,
        slot: u8,
    ) -> __sdk::Result<()> {
        self.create_starting_character_then(
            owner_key,
            generator_version,
            seed,
            age_tier,
            slot,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_starting_character` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_starting_character_then(
        &self,
        owner_key: String,
        generator_version: u16,
        seed: String,
        age_tier: StartingAgeTierCoordinate,
        slot: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl create_starting_character for super::RemoteReducers {
    fn create_starting_character_then(
        &self,
        owner_key: String,
        generator_version: u16,
        seed: String,
        age_tier: StartingAgeTierCoordinate,
        slot: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateStartingCharacterArgs {
                owner_key,
                generator_version,
                seed,
                age_tier,
                slot,
            },
            callback,
        )
    }
}
