// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DefineWeaponArgs {
    pub item_id: String,
    pub weight: f32,
    pub accuracy: f32,
    pub penetration: f32,
    pub reach: f32,
    pub balance: f32,
    pub precise: bool,
    pub melee: bool,
    pub ranged: bool,
    pub blunt: bool,
    pub slash: bool,
    pub pierce: bool,
}

impl From<DefineWeaponArgs> for super::Reducer {
    fn from(args: DefineWeaponArgs) -> Self {
        Self::DefineWeapon {
            item_id: args.item_id,
            weight: args.weight,
            accuracy: args.accuracy,
            penetration: args.penetration,
            reach: args.reach,
            balance: args.balance,
            precise: args.precise,
            melee: args.melee,
            ranged: args.ranged,
            blunt: args.blunt,
            slash: args.slash,
            pierce: args.pierce,
        }
    }
}

impl __sdk::InModule for DefineWeaponArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `define_weapon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait define_weapon {
    /// Request that the remote module invoke the reducer `define_weapon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`define_weapon:define_weapon_then`] to run a callback after the reducer completes.
    fn define_weapon(
        &self,
        item_id: String,
        weight: f32,
        accuracy: f32,
        penetration: f32,
        reach: f32,
        balance: f32,
        precise: bool,
        melee: bool,
        ranged: bool,
        blunt: bool,
        slash: bool,
        pierce: bool,
    ) -> __sdk::Result<()> {
        self.define_weapon_then(
            item_id,
            weight,
            accuracy,
            penetration,
            reach,
            balance,
            precise,
            melee,
            ranged,
            blunt,
            slash,
            pierce,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `define_weapon` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn define_weapon_then(
        &self,
        item_id: String,
        weight: f32,
        accuracy: f32,
        penetration: f32,
        reach: f32,
        balance: f32,
        precise: bool,
        melee: bool,
        ranged: bool,
        blunt: bool,
        slash: bool,
        pierce: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl define_weapon for super::RemoteReducers {
    fn define_weapon_then(
        &self,
        item_id: String,
        weight: f32,
        accuracy: f32,
        penetration: f32,
        reach: f32,
        balance: f32,
        precise: bool,
        melee: bool,
        ranged: bool,
        blunt: bool,
        slash: bool,
        pierce: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DefineWeaponArgs {
                item_id,
                weight,
                accuracy,
                penetration,
                reach,
                balance,
                precise,
                melee,
                ranged,
                blunt,
                slash,
                pierce,
            },
            callback,
        )
    }
}
