// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DevBootstrapSettlementActivityArgs {
    pub bootstrap_token: String,
    pub index: u32,
}

impl From<DevBootstrapSettlementActivityArgs> for super::Reducer {
    fn from(args: DevBootstrapSettlementActivityArgs) -> Self {
        Self::DevBootstrapSettlementActivity {
            bootstrap_token: args.bootstrap_token,
            index: args.index,
        }
    }
}

impl __sdk::InModule for DevBootstrapSettlementActivityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `dev_bootstrap_settlement_activity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait dev_bootstrap_settlement_activity {
    /// Request that the remote module invoke the reducer `dev_bootstrap_settlement_activity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`dev_bootstrap_settlement_activity:dev_bootstrap_settlement_activity_then`] to run a callback after the reducer completes.
    fn dev_bootstrap_settlement_activity(
        &self,
        bootstrap_token: String,
        index: u32,
    ) -> __sdk::Result<()> {
        self.dev_bootstrap_settlement_activity_then(bootstrap_token, index, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `dev_bootstrap_settlement_activity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn dev_bootstrap_settlement_activity_then(
        &self,
        bootstrap_token: String,
        index: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl dev_bootstrap_settlement_activity for super::RemoteReducers {
    fn dev_bootstrap_settlement_activity_then(
        &self,
        bootstrap_token: String,
        index: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DevBootstrapSettlementActivityArgs {
                bootstrap_token,
                index,
            },
            callback,
        )
    }
}
