// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DevelopmentScenarioBrowserAccess {
    pub id: String,
    pub scan_id: u64,
    pub owner_key: String,
    pub character_id: u64,
    pub scenario_slug: String,
    pub granted_micros: i64,
}

impl __sdk::InModule for DevelopmentScenarioBrowserAccess {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DevelopmentScenarioBrowserAccess`.
///
/// Provides typed access to columns for query building.
pub struct DevelopmentScenarioBrowserAccessCols {
    pub id: __sdk::__query_builder::Col<DevelopmentScenarioBrowserAccess, String>,
    pub scan_id: __sdk::__query_builder::Col<DevelopmentScenarioBrowserAccess, u64>,
    pub owner_key: __sdk::__query_builder::Col<DevelopmentScenarioBrowserAccess, String>,
    pub character_id: __sdk::__query_builder::Col<DevelopmentScenarioBrowserAccess, u64>,
    pub scenario_slug: __sdk::__query_builder::Col<DevelopmentScenarioBrowserAccess, String>,
    pub granted_micros: __sdk::__query_builder::Col<DevelopmentScenarioBrowserAccess, i64>,
}

impl __sdk::__query_builder::HasCols for DevelopmentScenarioBrowserAccess {
    type Cols = DevelopmentScenarioBrowserAccessCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DevelopmentScenarioBrowserAccessCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            scan_id: __sdk::__query_builder::Col::new(table_name, "scan_id"),
            owner_key: __sdk::__query_builder::Col::new(table_name, "owner_key"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            scenario_slug: __sdk::__query_builder::Col::new(table_name, "scenario_slug"),
            granted_micros: __sdk::__query_builder::Col::new(table_name, "granted_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `DevelopmentScenarioBrowserAccess`.
///
/// Provides typed access to indexed columns for query building.
pub struct DevelopmentScenarioBrowserAccessIxCols {
    pub character_id: __sdk::__query_builder::IxCol<DevelopmentScenarioBrowserAccess, u64>,
    pub id: __sdk::__query_builder::IxCol<DevelopmentScenarioBrowserAccess, String>,
    pub owner_key: __sdk::__query_builder::IxCol<DevelopmentScenarioBrowserAccess, String>,
    pub scan_id: __sdk::__query_builder::IxCol<DevelopmentScenarioBrowserAccess, u64>,
}

impl __sdk::__query_builder::HasIxCols for DevelopmentScenarioBrowserAccess {
    type IxCols = DevelopmentScenarioBrowserAccessIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DevelopmentScenarioBrowserAccessIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner_key: __sdk::__query_builder::IxCol::new(table_name, "owner_key"),
            scan_id: __sdk::__query_builder::IxCol::new(table_name, "scan_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DevelopmentScenarioBrowserAccess {}
