// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DialoguePrompt {
    pub id: String,
    pub session_id: String,
    pub prompt_id: String,
    pub mode: String,
    pub respondent_role: String,
    pub resolution_policy: String,
    pub choices_json: String,
    pub state: String,
}

impl __sdk::InModule for DialoguePrompt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DialoguePrompt`.
///
/// Provides typed access to columns for query building.
pub struct DialoguePromptCols {
    pub id: __sdk::__query_builder::Col<DialoguePrompt, String>,
    pub session_id: __sdk::__query_builder::Col<DialoguePrompt, String>,
    pub prompt_id: __sdk::__query_builder::Col<DialoguePrompt, String>,
    pub mode: __sdk::__query_builder::Col<DialoguePrompt, String>,
    pub respondent_role: __sdk::__query_builder::Col<DialoguePrompt, String>,
    pub resolution_policy: __sdk::__query_builder::Col<DialoguePrompt, String>,
    pub choices_json: __sdk::__query_builder::Col<DialoguePrompt, String>,
    pub state: __sdk::__query_builder::Col<DialoguePrompt, String>,
}

impl __sdk::__query_builder::HasCols for DialoguePrompt {
    type Cols = DialoguePromptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DialoguePromptCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            prompt_id: __sdk::__query_builder::Col::new(table_name, "prompt_id"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            respondent_role: __sdk::__query_builder::Col::new(table_name, "respondent_role"),
            resolution_policy: __sdk::__query_builder::Col::new(table_name, "resolution_policy"),
            choices_json: __sdk::__query_builder::Col::new(table_name, "choices_json"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
        }
    }
}

/// Indexed column accessor struct for the table `DialoguePrompt`.
///
/// Provides typed access to indexed columns for query building.
pub struct DialoguePromptIxCols {
    pub id: __sdk::__query_builder::IxCol<DialoguePrompt, String>,
    pub session_id: __sdk::__query_builder::IxCol<DialoguePrompt, String>,
}

impl __sdk::__query_builder::HasIxCols for DialoguePrompt {
    type IxCols = DialoguePromptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DialoguePromptIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DialoguePrompt {}
