// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::built_settlement_cover_type::BuiltSettlementCover;
use super::cropland_cover_type::CroplandCover;
use super::pasture_cover_type::PastureCover;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum DirectHistoricalVegetationCover {
    BuiltSettlement(BuiltSettlementCover),

    Cropland(CroplandCover),

    Pasture(PastureCover),

}



impl __sdk::InModule for DirectHistoricalVegetationCover {
    type Module = super::RemoteModule;
}

