// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FinishWorldDataImportArgs {
    pub artifact_id: String,
}

impl From<FinishWorldDataImportArgs> for super::Reducer {
    fn from(args: FinishWorldDataImportArgs) -> Self {
        Self::FinishWorldDataImport {
            artifact_id: args.artifact_id,
        }
    }
}

impl __sdk::InModule for FinishWorldDataImportArgs {
    type Module = super::RemoteModule;
}

pub struct FinishWorldDataImportCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `finish_world_data_import`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait finish_world_data_import {
    /// Request that the remote module invoke the reducer `finish_world_data_import` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_finish_world_data_import`] callbacks.
    fn finish_world_data_import(&self, artifact_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `finish_world_data_import`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`FinishWorldDataImportCallbackId`] can be passed to [`Self::remove_on_finish_world_data_import`]
    /// to cancel the callback.
    fn on_finish_world_data_import(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> FinishWorldDataImportCallbackId;
    /// Cancel a callback previously registered by [`Self::on_finish_world_data_import`],
    /// causing it not to run in the future.
    fn remove_on_finish_world_data_import(&self, callback: FinishWorldDataImportCallbackId);
}

impl finish_world_data_import for super::RemoteReducers {
    fn finish_world_data_import(&self, artifact_id: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "finish_world_data_import",
            FinishWorldDataImportArgs { artifact_id },
        )
    }
    fn on_finish_world_data_import(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> FinishWorldDataImportCallbackId {
        FinishWorldDataImportCallbackId(self.imp.on_reducer(
            "finish_world_data_import",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::FinishWorldDataImport { artifact_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, artifact_id)
            }),
        ))
    }
    fn remove_on_finish_world_data_import(&self, callback: FinishWorldDataImportCallbackId) {
        self.imp
            .remove_on_reducer("finish_world_data_import", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `finish_world_data_import`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_finish_world_data_import {
    /// Set the call-reducer flags for the reducer `finish_world_data_import` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn finish_world_data_import(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_finish_world_data_import for super::SetReducerFlags {
    fn finish_world_data_import(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("finish_world_data_import", flags);
    }
}
