// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ForgeWeaponArgs {
    pub character_id: u64,
    pub settlement_id: String,
    pub recipe: Vec<u8>,
}

impl From<ForgeWeaponArgs> for super::Reducer {
    fn from(args: ForgeWeaponArgs) -> Self {
        Self::ForgeWeapon {
            character_id: args.character_id,
            settlement_id: args.settlement_id,
            recipe: args.recipe,
        }
    }
}

impl __sdk::InModule for ForgeWeaponArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `forge_weapon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait forge_weapon {
    /// Request that the remote module invoke the reducer `forge_weapon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`forge_weapon:forge_weapon_then`] to run a callback after the reducer completes.
    fn forge_weapon(
        &self,
        character_id: u64,
        settlement_id: String,
        recipe: Vec<u8>,
    ) -> __sdk::Result<()> {
        self.forge_weapon_then(character_id, settlement_id, recipe, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `forge_weapon` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn forge_weapon_then(
        &self,
        character_id: u64,
        settlement_id: String,
        recipe: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl forge_weapon for super::RemoteReducers {
    fn forge_weapon_then(
        &self,
        character_id: u64,
        settlement_id: String,
        recipe: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ForgeWeaponArgs {
                character_id,
                settlement_id,
                recipe,
            },
            callback,
        )
    }
}
