// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::travel_edge_import_type::TravelEdgeImport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportTravelEdgesArgs {
    pub edges: Vec<TravelEdgeImport>,
}

impl From<ImportTravelEdgesArgs> for super::Reducer {
    fn from(args: ImportTravelEdgesArgs) -> Self {
        Self::ImportTravelEdges { edges: args.edges }
    }
}

impl __sdk::InModule for ImportTravelEdgesArgs {
    type Module = super::RemoteModule;
}

pub struct ImportTravelEdgesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_travel_edges`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_travel_edges {
    /// Request that the remote module invoke the reducer `import_travel_edges` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_import_travel_edges`] callbacks.
    fn import_travel_edges(&self, edges: Vec<TravelEdgeImport>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `import_travel_edges`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ImportTravelEdgesCallbackId`] can be passed to [`Self::remove_on_import_travel_edges`]
    /// to cancel the callback.
    fn on_import_travel_edges(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<TravelEdgeImport>) + Send + 'static,
    ) -> ImportTravelEdgesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_import_travel_edges`],
    /// causing it not to run in the future.
    fn remove_on_import_travel_edges(&self, callback: ImportTravelEdgesCallbackId);
}

impl import_travel_edges for super::RemoteReducers {
    fn import_travel_edges(&self, edges: Vec<TravelEdgeImport>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("import_travel_edges", ImportTravelEdgesArgs { edges })
    }
    fn on_import_travel_edges(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<TravelEdgeImport>) + Send + 'static,
    ) -> ImportTravelEdgesCallbackId {
        ImportTravelEdgesCallbackId(self.imp.on_reducer(
            "import_travel_edges",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ImportTravelEdges { edges },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, edges)
            }),
        ))
    }
    fn remove_on_import_travel_edges(&self, callback: ImportTravelEdgesCallbackId) {
        self.imp
            .remove_on_reducer("import_travel_edges", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `import_travel_edges`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_import_travel_edges {
    /// Set the call-reducer flags for the reducer `import_travel_edges` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn import_travel_edges(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_import_travel_edges for super::SetReducerFlags {
    fn import_travel_edges(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("import_travel_edges", flags);
    }
}
