// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct IngredientPreparationAttemptState {
    pub key: String,
    pub next_generation: u64,
    pub completed: bool,
}

impl __sdk::InModule for IngredientPreparationAttemptState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `IngredientPreparationAttemptState`.
///
/// Provides typed access to columns for query building.
pub struct IngredientPreparationAttemptStateCols {
    pub key: __sdk::__query_builder::Col<IngredientPreparationAttemptState, String>,
    pub next_generation: __sdk::__query_builder::Col<IngredientPreparationAttemptState, u64>,
    pub completed: __sdk::__query_builder::Col<IngredientPreparationAttemptState, bool>,
}

impl __sdk::__query_builder::HasCols for IngredientPreparationAttemptState {
    type Cols = IngredientPreparationAttemptStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        IngredientPreparationAttemptStateCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            next_generation: __sdk::__query_builder::Col::new(table_name, "next_generation"),
            completed: __sdk::__query_builder::Col::new(table_name, "completed"),
        }
    }
}

/// Indexed column accessor struct for the table `IngredientPreparationAttemptState`.
///
/// Provides typed access to indexed columns for query building.
pub struct IngredientPreparationAttemptStateIxCols {
    pub key: __sdk::__query_builder::IxCol<IngredientPreparationAttemptState, String>,
}

impl __sdk::__query_builder::HasIxCols for IngredientPreparationAttemptState {
    type IxCols = IngredientPreparationAttemptStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        IngredientPreparationAttemptStateIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for IngredientPreparationAttemptState {}
