// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestigationGeneratedActionOutput {
    pub capability_id: String,
    pub outputs_json: String,
}

impl __sdk::InModule for InvestigationGeneratedActionOutput {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InvestigationGeneratedActionOutput`.
///
/// Provides typed access to columns for query building.
pub struct InvestigationGeneratedActionOutputCols {
    pub capability_id: __sdk::__query_builder::Col<InvestigationGeneratedActionOutput, String>,
    pub outputs_json: __sdk::__query_builder::Col<InvestigationGeneratedActionOutput, String>,
}

impl __sdk::__query_builder::HasCols for InvestigationGeneratedActionOutput {
    type Cols = InvestigationGeneratedActionOutputCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestigationGeneratedActionOutputCols {
            capability_id: __sdk::__query_builder::Col::new(table_name, "capability_id"),
            outputs_json: __sdk::__query_builder::Col::new(table_name, "outputs_json"),
        }
    }
}

/// Indexed column accessor struct for the table `InvestigationGeneratedActionOutput`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestigationGeneratedActionOutputIxCols {
    pub capability_id: __sdk::__query_builder::IxCol<InvestigationGeneratedActionOutput, String>,
}

impl __sdk::__query_builder::HasIxCols for InvestigationGeneratedActionOutput {
    type IxCols = InvestigationGeneratedActionOutputIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestigationGeneratedActionOutputIxCols {
            capability_id: __sdk::__query_builder::IxCol::new(table_name, "capability_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestigationGeneratedActionOutput {}
