// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestigationTestimonyBundle {
    pub id: String,
    pub case_id: String,
    pub witness_ref: String,
    pub reliability_json: String,
    pub stages_json: String,
}


impl __sdk::InModule for InvestigationTestimonyBundle {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `InvestigationTestimonyBundle`.
///
/// Provides typed access to columns for query building.
pub struct InvestigationTestimonyBundleCols {
    pub id: __sdk::__query_builder::Col<InvestigationTestimonyBundle, String>,
    pub case_id: __sdk::__query_builder::Col<InvestigationTestimonyBundle, String>,
    pub witness_ref: __sdk::__query_builder::Col<InvestigationTestimonyBundle, String>,
    pub reliability_json: __sdk::__query_builder::Col<InvestigationTestimonyBundle, String>,
    pub stages_json: __sdk::__query_builder::Col<InvestigationTestimonyBundle, String>,
}

impl __sdk::__query_builder::HasCols for InvestigationTestimonyBundle {
    type Cols = InvestigationTestimonyBundleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestigationTestimonyBundleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            case_id: __sdk::__query_builder::Col::new(table_name, "case_id"),
            witness_ref: __sdk::__query_builder::Col::new(table_name, "witness_ref"),
            reliability_json: __sdk::__query_builder::Col::new(table_name, "reliability_json"),
            stages_json: __sdk::__query_builder::Col::new(table_name, "stages_json"),

        }
    }
}

/// Indexed column accessor struct for the table `InvestigationTestimonyBundle`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestigationTestimonyBundleIxCols {
    pub id: __sdk::__query_builder::IxCol<InvestigationTestimonyBundle, String>,
}

impl __sdk::__query_builder::HasIxCols for InvestigationTestimonyBundle {
    type IxCols = InvestigationTestimonyBundleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestigationTestimonyBundleIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestigationTestimonyBundle {}

