// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::edge_progress_permille_type::EdgeProgressPermille;
use super::route_landform_kind_type::RouteLandformKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LocatedRouteLandform {
    pub progress: EdgeProgressPermille,
    pub kind: RouteLandformKind,
}


impl __sdk::InModule for LocatedRouteLandform {
    type Module = super::RemoteModule;
}

