// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LocalProblemRumorDelivery {
    pub id: String,
    pub character_id: u64,
    pub settlement_id: String,
    pub session_id: String,
    pub receipt_id: String,
    pub fragments_json: String,
}

impl __sdk::InModule for LocalProblemRumorDelivery {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LocalProblemRumorDelivery`.
///
/// Provides typed access to columns for query building.
pub struct LocalProblemRumorDeliveryCols {
    pub id: __sdk::__query_builder::Col<LocalProblemRumorDelivery, String>,
    pub character_id: __sdk::__query_builder::Col<LocalProblemRumorDelivery, u64>,
    pub settlement_id: __sdk::__query_builder::Col<LocalProblemRumorDelivery, String>,
    pub session_id: __sdk::__query_builder::Col<LocalProblemRumorDelivery, String>,
    pub receipt_id: __sdk::__query_builder::Col<LocalProblemRumorDelivery, String>,
    pub fragments_json: __sdk::__query_builder::Col<LocalProblemRumorDelivery, String>,
}

impl __sdk::__query_builder::HasCols for LocalProblemRumorDelivery {
    type Cols = LocalProblemRumorDeliveryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LocalProblemRumorDeliveryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            receipt_id: __sdk::__query_builder::Col::new(table_name, "receipt_id"),
            fragments_json: __sdk::__query_builder::Col::new(table_name, "fragments_json"),
        }
    }
}

/// Indexed column accessor struct for the table `LocalProblemRumorDelivery`.
///
/// Provides typed access to indexed columns for query building.
pub struct LocalProblemRumorDeliveryIxCols {
    pub character_id: __sdk::__query_builder::IxCol<LocalProblemRumorDelivery, u64>,
    pub id: __sdk::__query_builder::IxCol<LocalProblemRumorDelivery, String>,
    pub session_id: __sdk::__query_builder::IxCol<LocalProblemRumorDelivery, String>,
    pub settlement_id: __sdk::__query_builder::IxCol<LocalProblemRumorDelivery, String>,
}

impl __sdk::__query_builder::HasIxCols for LocalProblemRumorDelivery {
    type IxCols = LocalProblemRumorDeliveryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LocalProblemRumorDeliveryIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LocalProblemRumorDelivery {}
