// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::euro_veg_map_unit_code_type::EuroVegMapUnitCode;
use super::potential_vegetation_formation_type::PotentialVegetationFormation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MappedPotentialVegetation {
    pub unit: EuroVegMapUnitCode,
    pub formation: PotentialVegetationFormation,
}

impl __sdk::InModule for MappedPotentialVegetation {
    type Module = super::RemoteModule;
}
