// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.3 (commit 02449737ca3b29e7e39679fccbef541a50f32094).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod abandon_quest_reducer;
pub mod accept_quest_reducer;
pub mod add_and_equip_item_reducer;
pub mod cancel_mission_request_reducer;
pub mod change_inventory_item_reducer;
pub mod character_attributes_table;
pub mod character_attributes_type;
pub mod character_equip_table;
pub mod character_equip_type;
pub mod character_limbs_table;
pub mod character_limbs_type;
pub mod character_skills_table;
pub mod character_skills_type;
pub mod character_stats_table;
pub mod character_stats_type;
pub mod character_table;
pub mod character_type;
pub mod clear_deployment_session_reducer;
pub mod complete_quest_reducer;
pub mod connected_player_item_type;
pub mod connected_player_type;
pub mod connected_players_table;
pub mod create_character_reducer;
pub mod create_named_character_reducer;
pub mod create_named_character_with_id_reducer;
pub mod create_party_reducer;
pub mod create_tactical_server_for_request_reducer;
pub mod create_tactical_server_reducer;
pub mod define_armor_reducer;
pub mod define_item_reducer;
pub mod define_shield_reducer;
pub mod define_weapon_reducer;
pub mod deployment_session_table;
pub mod deployment_session_type;
pub mod disband_party_reducer;
pub mod end_tactical_server_by_instance_reducer;
pub mod end_tactical_server_reducer;
pub mod enter_mission_reducer;
pub mod equip_item_reducer;
pub mod insert_new_character_reducer;
pub mod inventory_item_table;
pub mod inventory_item_type;
pub mod item_kind_type;
pub mod item_slot_type;
pub mod item_table;
pub mod item_type;
pub mod join_party_reducer;
pub mod leave_mission_reducer;
pub mod leave_party_reducer;
pub mod mission_failed_reducer;
pub mod party_member_table;
pub mod party_member_type;
pub mod party_table;
pub mod party_type;
pub mod quest_status_type;
pub mod quest_table;
pub mod quest_type;
pub mod register_deployment_session_reducer;
pub mod request_tactical_server_for_scene_reducer;
pub mod request_tactical_server_reducer;
pub mod seed_world_reducer;
pub mod settlement_table;
pub mod settlement_type;
pub mod tactical_server_request_table;
pub mod tactical_server_request_type;
pub mod tactical_server_table;
pub mod tactical_server_type;
pub mod travel_to_settlement_reducer;
pub mod update_character_reducer;
pub mod update_deployment_session_status_reducer;

pub use abandon_quest_reducer::{
    abandon_quest, set_flags_for_abandon_quest, AbandonQuestCallbackId,
};
pub use accept_quest_reducer::{accept_quest, set_flags_for_accept_quest, AcceptQuestCallbackId};
pub use add_and_equip_item_reducer::{
    add_and_equip_item, set_flags_for_add_and_equip_item, AddAndEquipItemCallbackId,
};
pub use cancel_mission_request_reducer::{
    cancel_mission_request, set_flags_for_cancel_mission_request, CancelMissionRequestCallbackId,
};
pub use change_inventory_item_reducer::{
    change_inventory_item, set_flags_for_change_inventory_item, ChangeInventoryItemCallbackId,
};
pub use character_attributes_table::*;
pub use character_attributes_type::CharacterAttributes;
pub use character_equip_table::*;
pub use character_equip_type::CharacterEquip;
pub use character_limbs_table::*;
pub use character_limbs_type::CharacterLimbs;
pub use character_skills_table::*;
pub use character_skills_type::CharacterSkills;
pub use character_stats_table::*;
pub use character_stats_type::CharacterStats;
pub use character_table::*;
pub use character_type::Character;
pub use clear_deployment_session_reducer::{
    clear_deployment_session, set_flags_for_clear_deployment_session,
    ClearDeploymentSessionCallbackId,
};
pub use complete_quest_reducer::{
    complete_quest, set_flags_for_complete_quest, CompleteQuestCallbackId,
};
pub use connected_player_item_type::ConnectedPlayerItem;
pub use connected_player_type::ConnectedPlayer;
pub use connected_players_table::*;
pub use create_character_reducer::{
    create_character, set_flags_for_create_character, CreateCharacterCallbackId,
};
pub use create_named_character_reducer::{
    create_named_character, set_flags_for_create_named_character, CreateNamedCharacterCallbackId,
};
pub use create_named_character_with_id_reducer::{
    create_named_character_with_id, set_flags_for_create_named_character_with_id,
    CreateNamedCharacterWithIdCallbackId,
};
pub use create_party_reducer::{create_party, set_flags_for_create_party, CreatePartyCallbackId};
pub use create_tactical_server_for_request_reducer::{
    create_tactical_server_for_request, set_flags_for_create_tactical_server_for_request,
    CreateTacticalServerForRequestCallbackId,
};
pub use create_tactical_server_reducer::{
    create_tactical_server, set_flags_for_create_tactical_server, CreateTacticalServerCallbackId,
};
pub use define_armor_reducer::{define_armor, set_flags_for_define_armor, DefineArmorCallbackId};
pub use define_item_reducer::{define_item, set_flags_for_define_item, DefineItemCallbackId};
pub use define_shield_reducer::{
    define_shield, set_flags_for_define_shield, DefineShieldCallbackId,
};
pub use define_weapon_reducer::{
    define_weapon, set_flags_for_define_weapon, DefineWeaponCallbackId,
};
pub use deployment_session_table::*;
pub use deployment_session_type::DeploymentSession;
pub use disband_party_reducer::{
    disband_party, set_flags_for_disband_party, DisbandPartyCallbackId,
};
pub use end_tactical_server_by_instance_reducer::{
    end_tactical_server_by_instance, set_flags_for_end_tactical_server_by_instance,
    EndTacticalServerByInstanceCallbackId,
};
pub use end_tactical_server_reducer::{
    end_tactical_server, set_flags_for_end_tactical_server, EndTacticalServerCallbackId,
};
pub use enter_mission_reducer::{
    enter_mission, set_flags_for_enter_mission, EnterMissionCallbackId,
};
pub use equip_item_reducer::{equip_item, set_flags_for_equip_item, EquipItemCallbackId};
pub use insert_new_character_reducer::{
    insert_new_character, set_flags_for_insert_new_character, InsertNewCharacterCallbackId,
};
pub use inventory_item_table::*;
pub use inventory_item_type::InventoryItem;
pub use item_kind_type::ItemKind;
pub use item_slot_type::ItemSlot;
pub use item_table::*;
pub use item_type::Item;
pub use join_party_reducer::{join_party, set_flags_for_join_party, JoinPartyCallbackId};
pub use leave_mission_reducer::{
    leave_mission, set_flags_for_leave_mission, LeaveMissionCallbackId,
};
pub use leave_party_reducer::{leave_party, set_flags_for_leave_party, LeavePartyCallbackId};
pub use mission_failed_reducer::{
    mission_failed, set_flags_for_mission_failed, MissionFailedCallbackId,
};
pub use party_member_table::*;
pub use party_member_type::PartyMember;
pub use party_table::*;
pub use party_type::Party;
pub use quest_status_type::QuestStatus;
pub use quest_table::*;
pub use quest_type::Quest;
pub use register_deployment_session_reducer::{
    register_deployment_session, set_flags_for_register_deployment_session,
    RegisterDeploymentSessionCallbackId,
};
pub use request_tactical_server_for_scene_reducer::{
    request_tactical_server_for_scene, set_flags_for_request_tactical_server_for_scene,
    RequestTacticalServerForSceneCallbackId,
};
pub use request_tactical_server_reducer::{
    request_tactical_server, set_flags_for_request_tactical_server, RequestTacticalServerCallbackId,
};
pub use seed_world_reducer::{seed_world, set_flags_for_seed_world, SeedWorldCallbackId};
pub use settlement_table::*;
pub use settlement_type::Settlement;
pub use tactical_server_request_table::*;
pub use tactical_server_request_type::TacticalServerRequest;
pub use tactical_server_table::*;
pub use tactical_server_type::TacticalServer;
pub use travel_to_settlement_reducer::{
    set_flags_for_travel_to_settlement, travel_to_settlement, TravelToSettlementCallbackId,
};
pub use update_character_reducer::{
    set_flags_for_update_character, update_character, UpdateCharacterCallbackId,
};
pub use update_deployment_session_status_reducer::{
    set_flags_for_update_deployment_session_status, update_deployment_session_status,
    UpdateDeploymentSessionStatusCallbackId,
};

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AbandonQuest {
        character_id: u64,
        quest_id: String,
    },
    AcceptQuest {
        character_id: u64,
        quest_id: String,
    },
    AddAndEquipItem {
        character_id: u64,
        item_id: String,
        destination: ItemSlot,
    },
    CancelMissionRequest {
        mission_id: String,
    },
    ChangeInventoryItem {
        character_id: u64,
        item_id: String,
        by_quantity: i32,
    },
    ClearDeploymentSession {
        mission_id: String,
    },
    CompleteQuest {
        quest_id: String,
    },
    CreateCharacter {
        id: u64,
    },
    CreateNamedCharacter {
        name: String,
    },
    CreateNamedCharacterWithId {
        id: u64,
        name: String,
    },
    CreateParty {
        id: String,
        name: String,
        leader_id: u64,
    },
    CreateTacticalServer {
        mission_id: String,
        scene_key: String,
        addr: String,
        cert_digest: String,
    },
    CreateTacticalServerForRequest {
        mission_id: String,
        addr: String,
        cert_digest: String,
    },
    DefineArmor {
        item_id: String,
        weight: f32,
        slot: ItemSlot,
        dodge: f32,
        coverage: f32,
    },
    DefineItem {
        item_id: String,
        weight: f32,
    },
    DefineShield {
        item_id: String,
        weight: f32,
        block: f32,
    },
    DefineWeapon {
        item_id: String,
        weight: f32,
        accuracy: f32,
    },
    DisbandParty {
        party_id: String,
    },
    EndTacticalServer {
        success: bool,
        xp_gained: i32,
    },
    EndTacticalServerByInstance {
        server: TacticalServer,
        success: bool,
        xp_gained: i32,
    },
    EnterMission {
        character_id: u64,
        server: __sdk::Identity,
    },
    EquipItem {
        character_id: u64,
        inventory_item_id: u64,
        destination: ItemSlot,
    },
    InsertNewCharacter {
        name: String,
        id: u64,
    },
    JoinParty {
        character_id: u64,
        party_id: String,
    },
    LeaveMission {
        character_id: u64,
    },
    LeaveParty {
        character_id: u64,
    },
    MissionFailed {
        mission_id: String,
        reason: String,
    },
    RegisterDeploymentSession {
        mission_id: String,
        request_id: String,
        party_id: String,
    },
    RequestTacticalServer {
        mission_id: String,
        scene_key: String,
    },
    RequestTacticalServerForScene {
        scene_key: String,
    },
    SeedWorld,
    TravelToSettlement {
        character_id: u64,
        settlement_id: String,
    },
    UpdateCharacter {
        id: u64,
        name: String,
    },
    UpdateDeploymentSessionStatus {
        mission_id: String,
        status: String,
        last_error: Option<String>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AbandonQuest { .. } => "abandon_quest",
            Reducer::AcceptQuest { .. } => "accept_quest",
            Reducer::AddAndEquipItem { .. } => "add_and_equip_item",
            Reducer::CancelMissionRequest { .. } => "cancel_mission_request",
            Reducer::ChangeInventoryItem { .. } => "change_inventory_item",
            Reducer::ClearDeploymentSession { .. } => "clear_deployment_session",
            Reducer::CompleteQuest { .. } => "complete_quest",
            Reducer::CreateCharacter { .. } => "create_character",
            Reducer::CreateNamedCharacter { .. } => "create_named_character",
            Reducer::CreateNamedCharacterWithId { .. } => "create_named_character_with_id",
            Reducer::CreateParty { .. } => "create_party",
            Reducer::CreateTacticalServer { .. } => "create_tactical_server",
            Reducer::CreateTacticalServerForRequest { .. } => "create_tactical_server_for_request",
            Reducer::DefineArmor { .. } => "define_armor",
            Reducer::DefineItem { .. } => "define_item",
            Reducer::DefineShield { .. } => "define_shield",
            Reducer::DefineWeapon { .. } => "define_weapon",
            Reducer::DisbandParty { .. } => "disband_party",
            Reducer::EndTacticalServer { .. } => "end_tactical_server",
            Reducer::EndTacticalServerByInstance { .. } => "end_tactical_server_by_instance",
            Reducer::EnterMission { .. } => "enter_mission",
            Reducer::EquipItem { .. } => "equip_item",
            Reducer::InsertNewCharacter { .. } => "insert_new_character",
            Reducer::JoinParty { .. } => "join_party",
            Reducer::LeaveMission { .. } => "leave_mission",
            Reducer::LeaveParty { .. } => "leave_party",
            Reducer::MissionFailed { .. } => "mission_failed",
            Reducer::RegisterDeploymentSession { .. } => "register_deployment_session",
            Reducer::RequestTacticalServer { .. } => "request_tactical_server",
            Reducer::RequestTacticalServerForScene { .. } => "request_tactical_server_for_scene",
            Reducer::SeedWorld => "seed_world",
            Reducer::TravelToSettlement { .. } => "travel_to_settlement",
            Reducer::UpdateCharacter { .. } => "update_character",
            Reducer::UpdateDeploymentSessionStatus { .. } => "update_deployment_session_status",
            _ => unreachable!(),
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "abandon_quest" => Ok(__sdk::parse_reducer_args::<
                abandon_quest_reducer::AbandonQuestArgs,
            >("abandon_quest", &value.args)?
            .into()),
            "accept_quest" => Ok(
                __sdk::parse_reducer_args::<accept_quest_reducer::AcceptQuestArgs>(
                    "accept_quest",
                    &value.args,
                )?
                .into(),
            ),
            "add_and_equip_item" => Ok(__sdk::parse_reducer_args::<
                add_and_equip_item_reducer::AddAndEquipItemArgs,
            >("add_and_equip_item", &value.args)?
            .into()),
            "cancel_mission_request" => Ok(__sdk::parse_reducer_args::<
                cancel_mission_request_reducer::CancelMissionRequestArgs,
            >("cancel_mission_request", &value.args)?
            .into()),
            "change_inventory_item" => Ok(__sdk::parse_reducer_args::<
                change_inventory_item_reducer::ChangeInventoryItemArgs,
            >("change_inventory_item", &value.args)?
            .into()),
            "clear_deployment_session" => {
                Ok(__sdk::parse_reducer_args::<
                    clear_deployment_session_reducer::ClearDeploymentSessionArgs,
                >("clear_deployment_session", &value.args)?
                .into())
            }
            "complete_quest" => Ok(__sdk::parse_reducer_args::<
                complete_quest_reducer::CompleteQuestArgs,
            >("complete_quest", &value.args)?
            .into()),
            "create_character" => Ok(__sdk::parse_reducer_args::<
                create_character_reducer::CreateCharacterArgs,
            >("create_character", &value.args)?
            .into()),
            "create_named_character" => Ok(__sdk::parse_reducer_args::<
                create_named_character_reducer::CreateNamedCharacterArgs,
            >("create_named_character", &value.args)?
            .into()),
            "create_named_character_with_id" => {
                Ok(__sdk::parse_reducer_args::<
                    create_named_character_with_id_reducer::CreateNamedCharacterWithIdArgs,
                >("create_named_character_with_id", &value.args)?
                .into())
            }
            "create_party" => Ok(
                __sdk::parse_reducer_args::<create_party_reducer::CreatePartyArgs>(
                    "create_party",
                    &value.args,
                )?
                .into(),
            ),
            "create_tactical_server" => Ok(__sdk::parse_reducer_args::<
                create_tactical_server_reducer::CreateTacticalServerArgs,
            >("create_tactical_server", &value.args)?
            .into()),
            "create_tactical_server_for_request" => {
                Ok(__sdk::parse_reducer_args::<
                    create_tactical_server_for_request_reducer::CreateTacticalServerForRequestArgs,
                >("create_tactical_server_for_request", &value.args)?
                .into())
            }
            "define_armor" => Ok(
                __sdk::parse_reducer_args::<define_armor_reducer::DefineArmorArgs>(
                    "define_armor",
                    &value.args,
                )?
                .into(),
            ),
            "define_item" => Ok(
                __sdk::parse_reducer_args::<define_item_reducer::DefineItemArgs>(
                    "define_item",
                    &value.args,
                )?
                .into(),
            ),
            "define_shield" => Ok(__sdk::parse_reducer_args::<
                define_shield_reducer::DefineShieldArgs,
            >("define_shield", &value.args)?
            .into()),
            "define_weapon" => Ok(__sdk::parse_reducer_args::<
                define_weapon_reducer::DefineWeaponArgs,
            >("define_weapon", &value.args)?
            .into()),
            "disband_party" => Ok(__sdk::parse_reducer_args::<
                disband_party_reducer::DisbandPartyArgs,
            >("disband_party", &value.args)?
            .into()),
            "end_tactical_server" => Ok(__sdk::parse_reducer_args::<
                end_tactical_server_reducer::EndTacticalServerArgs,
            >("end_tactical_server", &value.args)?
            .into()),
            "end_tactical_server_by_instance" => {
                Ok(__sdk::parse_reducer_args::<
                    end_tactical_server_by_instance_reducer::EndTacticalServerByInstanceArgs,
                >("end_tactical_server_by_instance", &value.args)?
                .into())
            }
            "enter_mission" => Ok(__sdk::parse_reducer_args::<
                enter_mission_reducer::EnterMissionArgs,
            >("enter_mission", &value.args)?
            .into()),
            "equip_item" => Ok(
                __sdk::parse_reducer_args::<equip_item_reducer::EquipItemArgs>(
                    "equip_item",
                    &value.args,
                )?
                .into(),
            ),
            "insert_new_character" => Ok(__sdk::parse_reducer_args::<
                insert_new_character_reducer::InsertNewCharacterArgs,
            >("insert_new_character", &value.args)?
            .into()),
            "join_party" => Ok(
                __sdk::parse_reducer_args::<join_party_reducer::JoinPartyArgs>(
                    "join_party",
                    &value.args,
                )?
                .into(),
            ),
            "leave_mission" => Ok(__sdk::parse_reducer_args::<
                leave_mission_reducer::LeaveMissionArgs,
            >("leave_mission", &value.args)?
            .into()),
            "leave_party" => Ok(
                __sdk::parse_reducer_args::<leave_party_reducer::LeavePartyArgs>(
                    "leave_party",
                    &value.args,
                )?
                .into(),
            ),
            "mission_failed" => Ok(__sdk::parse_reducer_args::<
                mission_failed_reducer::MissionFailedArgs,
            >("mission_failed", &value.args)?
            .into()),
            "register_deployment_session" => {
                Ok(__sdk::parse_reducer_args::<
                    register_deployment_session_reducer::RegisterDeploymentSessionArgs,
                >("register_deployment_session", &value.args)?
                .into())
            }
            "request_tactical_server" => Ok(__sdk::parse_reducer_args::<
                request_tactical_server_reducer::RequestTacticalServerArgs,
            >("request_tactical_server", &value.args)?
            .into()),
            "request_tactical_server_for_scene" => {
                Ok(__sdk::parse_reducer_args::<
                    request_tactical_server_for_scene_reducer::RequestTacticalServerForSceneArgs,
                >("request_tactical_server_for_scene", &value.args)?
                .into())
            }
            "seed_world" => Ok(
                __sdk::parse_reducer_args::<seed_world_reducer::SeedWorldArgs>(
                    "seed_world",
                    &value.args,
                )?
                .into(),
            ),
            "travel_to_settlement" => Ok(__sdk::parse_reducer_args::<
                travel_to_settlement_reducer::TravelToSettlementArgs,
            >("travel_to_settlement", &value.args)?
            .into()),
            "update_character" => Ok(__sdk::parse_reducer_args::<
                update_character_reducer::UpdateCharacterArgs,
            >("update_character", &value.args)?
            .into()),
            "update_deployment_session_status" => {
                Ok(__sdk::parse_reducer_args::<
                    update_deployment_session_status_reducer::UpdateDeploymentSessionStatusArgs,
                >("update_deployment_session_status", &value.args)?
                .into())
            }
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    character: __sdk::TableUpdate<Character>,
    character_attributes: __sdk::TableUpdate<CharacterAttributes>,
    character_equip: __sdk::TableUpdate<CharacterEquip>,
    character_limbs: __sdk::TableUpdate<CharacterLimbs>,
    character_skills: __sdk::TableUpdate<CharacterSkills>,
    character_stats: __sdk::TableUpdate<CharacterStats>,
    connected_players: __sdk::TableUpdate<ConnectedPlayer>,
    deployment_session: __sdk::TableUpdate<DeploymentSession>,
    inventory_item: __sdk::TableUpdate<InventoryItem>,
    item: __sdk::TableUpdate<Item>,
    party: __sdk::TableUpdate<Party>,
    party_member: __sdk::TableUpdate<PartyMember>,
    quest: __sdk::TableUpdate<Quest>,
    settlement: __sdk::TableUpdate<Settlement>,
    tactical_server: __sdk::TableUpdate<TacticalServer>,
    tactical_server_request: __sdk::TableUpdate<TacticalServerRequest>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "character" => db_update
                    .character
                    .append(character_table::parse_table_update(table_update)?),
                "character_attributes" => db_update.character_attributes.append(
                    character_attributes_table::parse_table_update(table_update)?,
                ),
                "character_equip" => db_update
                    .character_equip
                    .append(character_equip_table::parse_table_update(table_update)?),
                "character_limbs" => db_update
                    .character_limbs
                    .append(character_limbs_table::parse_table_update(table_update)?),
                "character_skills" => db_update
                    .character_skills
                    .append(character_skills_table::parse_table_update(table_update)?),
                "character_stats" => db_update
                    .character_stats
                    .append(character_stats_table::parse_table_update(table_update)?),
                "connected_players" => db_update
                    .connected_players
                    .append(connected_players_table::parse_table_update(table_update)?),
                "deployment_session" => db_update
                    .deployment_session
                    .append(deployment_session_table::parse_table_update(table_update)?),
                "inventory_item" => db_update
                    .inventory_item
                    .append(inventory_item_table::parse_table_update(table_update)?),
                "item" => db_update
                    .item
                    .append(item_table::parse_table_update(table_update)?),
                "party" => db_update
                    .party
                    .append(party_table::parse_table_update(table_update)?),
                "party_member" => db_update
                    .party_member
                    .append(party_member_table::parse_table_update(table_update)?),
                "quest" => db_update
                    .quest
                    .append(quest_table::parse_table_update(table_update)?),
                "settlement" => db_update
                    .settlement
                    .append(settlement_table::parse_table_update(table_update)?),
                "tactical_server" => db_update
                    .tactical_server
                    .append(tactical_server_table::parse_table_update(table_update)?),
                "tactical_server_request" => db_update.tactical_server_request.append(
                    tactical_server_request_table::parse_table_update(table_update)?,
                ),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.character = cache
            .apply_diff_to_table::<Character>("character", &self.character)
            .with_updates_by_pk(|row| &row.id);
        diff.character_attributes = cache.apply_diff_to_table::<CharacterAttributes>(
            "character_attributes",
            &self.character_attributes,
        );
        diff.character_equip =
            cache.apply_diff_to_table::<CharacterEquip>("character_equip", &self.character_equip);
        diff.character_limbs =
            cache.apply_diff_to_table::<CharacterLimbs>("character_limbs", &self.character_limbs);
        diff.character_skills = cache
            .apply_diff_to_table::<CharacterSkills>("character_skills", &self.character_skills);
        diff.character_stats =
            cache.apply_diff_to_table::<CharacterStats>("character_stats", &self.character_stats);
        diff.deployment_session = cache
            .apply_diff_to_table::<DeploymentSession>(
                "deployment_session",
                &self.deployment_session,
            )
            .with_updates_by_pk(|row| &row.mission_id);
        diff.inventory_item = cache
            .apply_diff_to_table::<InventoryItem>("inventory_item", &self.inventory_item)
            .with_updates_by_pk(|row| &row.id);
        diff.item = cache
            .apply_diff_to_table::<Item>("item", &self.item)
            .with_updates_by_pk(|row| &row.id);
        diff.party = cache
            .apply_diff_to_table::<Party>("party", &self.party)
            .with_updates_by_pk(|row| &row.id);
        diff.party_member = cache
            .apply_diff_to_table::<PartyMember>("party_member", &self.party_member)
            .with_updates_by_pk(|row| &row.id);
        diff.quest = cache
            .apply_diff_to_table::<Quest>("quest", &self.quest)
            .with_updates_by_pk(|row| &row.id);
        diff.settlement = cache
            .apply_diff_to_table::<Settlement>("settlement", &self.settlement)
            .with_updates_by_pk(|row| &row.id);
        diff.tactical_server = cache
            .apply_diff_to_table::<TacticalServer>("tactical_server", &self.tactical_server)
            .with_updates_by_pk(|row| &row.identity);
        diff.tactical_server_request = cache
            .apply_diff_to_table::<TacticalServerRequest>(
                "tactical_server_request",
                &self.tactical_server_request,
            )
            .with_updates_by_pk(|row| &row.mission_id);
        diff.connected_players = cache
            .apply_diff_to_table::<ConnectedPlayer>("connected_players", &self.connected_players);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    character: __sdk::TableAppliedDiff<'r, Character>,
    character_attributes: __sdk::TableAppliedDiff<'r, CharacterAttributes>,
    character_equip: __sdk::TableAppliedDiff<'r, CharacterEquip>,
    character_limbs: __sdk::TableAppliedDiff<'r, CharacterLimbs>,
    character_skills: __sdk::TableAppliedDiff<'r, CharacterSkills>,
    character_stats: __sdk::TableAppliedDiff<'r, CharacterStats>,
    connected_players: __sdk::TableAppliedDiff<'r, ConnectedPlayer>,
    deployment_session: __sdk::TableAppliedDiff<'r, DeploymentSession>,
    inventory_item: __sdk::TableAppliedDiff<'r, InventoryItem>,
    item: __sdk::TableAppliedDiff<'r, Item>,
    party: __sdk::TableAppliedDiff<'r, Party>,
    party_member: __sdk::TableAppliedDiff<'r, PartyMember>,
    quest: __sdk::TableAppliedDiff<'r, Quest>,
    settlement: __sdk::TableAppliedDiff<'r, Settlement>,
    tactical_server: __sdk::TableAppliedDiff<'r, TacticalServer>,
    tactical_server_request: __sdk::TableAppliedDiff<'r, TacticalServerRequest>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Character>("character", &self.character, event);
        callbacks.invoke_table_row_callbacks::<CharacterAttributes>(
            "character_attributes",
            &self.character_attributes,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CharacterEquip>(
            "character_equip",
            &self.character_equip,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CharacterLimbs>(
            "character_limbs",
            &self.character_limbs,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CharacterSkills>(
            "character_skills",
            &self.character_skills,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CharacterStats>(
            "character_stats",
            &self.character_stats,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ConnectedPlayer>(
            "connected_players",
            &self.connected_players,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DeploymentSession>(
            "deployment_session",
            &self.deployment_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<InventoryItem>(
            "inventory_item",
            &self.inventory_item,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Item>("item", &self.item, event);
        callbacks.invoke_table_row_callbacks::<Party>("party", &self.party, event);
        callbacks.invoke_table_row_callbacks::<PartyMember>(
            "party_member",
            &self.party_member,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Quest>("quest", &self.quest, event);
        callbacks.invoke_table_row_callbacks::<Settlement>("settlement", &self.settlement, event);
        callbacks.invoke_table_row_callbacks::<TacticalServer>(
            "tactical_server",
            &self.tactical_server,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TacticalServerRequest>(
            "tactical_server_request",
            &self.tactical_server_request,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        character_table::register_table(client_cache);
        character_attributes_table::register_table(client_cache);
        character_equip_table::register_table(client_cache);
        character_limbs_table::register_table(client_cache);
        character_skills_table::register_table(client_cache);
        character_stats_table::register_table(client_cache);
        connected_players_table::register_table(client_cache);
        deployment_session_table::register_table(client_cache);
        inventory_item_table::register_table(client_cache);
        item_table::register_table(client_cache);
        party_table::register_table(client_cache);
        party_member_table::register_table(client_cache);
        quest_table::register_table(client_cache);
        settlement_table::register_table(client_cache);
        tactical_server_table::register_table(client_cache);
        tactical_server_request_table::register_table(client_cache);
    }
}
