// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NarrativeCombatFollowupAuthority {
    pub encounter_id: String,
    pub occurrence_id: String,
    pub party_id: String,
    pub initiating_character_id: u64,
    pub victory_result: String,
    pub defeat_result: String,
    pub escape_result: String,
    pub victory_effects_json: String,
    pub victory_personality_json: String,
    pub victory_quest_reward_tags: Vec<String>,
}

impl __sdk::InModule for NarrativeCombatFollowupAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NarrativeCombatFollowupAuthority`.
///
/// Provides typed access to columns for query building.
pub struct NarrativeCombatFollowupAuthorityCols {
    pub encounter_id: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub occurrence_id: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub party_id: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub initiating_character_id: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, u64>,
    pub victory_result: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub defeat_result: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub escape_result: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub victory_effects_json: __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub victory_personality_json:
        __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, String>,
    pub victory_quest_reward_tags:
        __sdk::__query_builder::Col<NarrativeCombatFollowupAuthority, Vec<String>>,
}

impl __sdk::__query_builder::HasCols for NarrativeCombatFollowupAuthority {
    type Cols = NarrativeCombatFollowupAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NarrativeCombatFollowupAuthorityCols {
            encounter_id: __sdk::__query_builder::Col::new(table_name, "encounter_id"),
            occurrence_id: __sdk::__query_builder::Col::new(table_name, "occurrence_id"),
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            initiating_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "initiating_character_id",
            ),
            victory_result: __sdk::__query_builder::Col::new(table_name, "victory_result"),
            defeat_result: __sdk::__query_builder::Col::new(table_name, "defeat_result"),
            escape_result: __sdk::__query_builder::Col::new(table_name, "escape_result"),
            victory_effects_json: __sdk::__query_builder::Col::new(
                table_name,
                "victory_effects_json",
            ),
            victory_personality_json: __sdk::__query_builder::Col::new(
                table_name,
                "victory_personality_json",
            ),
            victory_quest_reward_tags: __sdk::__query_builder::Col::new(
                table_name,
                "victory_quest_reward_tags",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `NarrativeCombatFollowupAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct NarrativeCombatFollowupAuthorityIxCols {
    pub encounter_id: __sdk::__query_builder::IxCol<NarrativeCombatFollowupAuthority, String>,
}

impl __sdk::__query_builder::HasIxCols for NarrativeCombatFollowupAuthority {
    type IxCols = NarrativeCombatFollowupAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NarrativeCombatFollowupAuthorityIxCols {
            encounter_id: __sdk::__query_builder::IxCol::new(table_name, "encounter_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NarrativeCombatFollowupAuthority {}
