// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::party_item_amount_type::PartyItemAmount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `party_item_amount`.
///
/// Obtain a handle from the [`PartyItemAmountTableAccess::party_item_amount`] method on [`super::RemoteTables`],
/// like `ctx.db.party_item_amount()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_item_amount().on_insert(...)`.
pub struct PartyItemAmountTableHandle<'ctx> {
    imp: __sdk::TableHandle<PartyItemAmount>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `party_item_amount`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PartyItemAmountTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PartyItemAmountTableHandle`], which mediates access to the table `party_item_amount`.
    fn party_item_amount(&self) -> PartyItemAmountTableHandle<'_>;
}

impl PartyItemAmountTableAccess for super::RemoteTables {
    fn party_item_amount(&self) -> PartyItemAmountTableHandle<'_> {
        PartyItemAmountTableHandle {
            imp: self.imp.get_table::<PartyItemAmount>("party_item_amount"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PartyItemAmountInsertCallbackId(__sdk::CallbackId);
pub struct PartyItemAmountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PartyItemAmountTableHandle<'ctx> {
    type Row = PartyItemAmount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyItemAmount> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PartyItemAmountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyItemAmountInsertCallbackId {
        PartyItemAmountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyItemAmountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PartyItemAmountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyItemAmountDeleteCallbackId {
        PartyItemAmountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyItemAmountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PartyItemAmountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PartyItemAmountTableHandle<'ctx> {
    type UpdateCallbackId = PartyItemAmountUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyItemAmountUpdateCallbackId {
        PartyItemAmountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyItemAmountUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `party_inventory_item_id` unique index on the table `party_item_amount`,
/// which allows point queries on the field of the same name
/// via the [`PartyItemAmountPartyInventoryItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_item_amount().party_inventory_item_id().find(...)`.
pub struct PartyItemAmountPartyInventoryItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PartyItemAmount, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PartyItemAmountTableHandle<'ctx> {
    /// Get a handle on the `party_inventory_item_id` unique index on the table `party_item_amount`.
    pub fn party_inventory_item_id(&self) -> PartyItemAmountPartyInventoryItemIdUnique<'ctx> {
        PartyItemAmountPartyInventoryItemIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<u64>("party_inventory_item_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PartyItemAmountPartyInventoryItemIdUnique<'ctx> {
    /// Find the subscribed row whose `party_inventory_item_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PartyItemAmount> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PartyItemAmount>("party_item_amount");
    _table.add_unique_constraint::<u64>("party_inventory_item_id", |row| {
        &row.party_inventory_item_id
    });
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PartyItemAmount>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PartyItemAmount>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PartyItemAmount`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait party_item_amountQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PartyItemAmount`.
    fn party_item_amount(&self) -> __sdk::__query_builder::Table<PartyItemAmount>;
}

impl party_item_amountQueryTableAccess for __sdk::QueryTableAccessor {
    fn party_item_amount(&self) -> __sdk::__query_builder::Table<PartyItemAmount> {
        __sdk::__query_builder::Table::new("party_item_amount")
    }
}
