// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::party_journey_type::PartyJourney;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `party_journey`.
///
/// Obtain a handle from the [`PartyJourneyTableAccess::party_journey`] method on [`super::RemoteTables`],
/// like `ctx.db.party_journey()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_journey().on_insert(...)`.
pub struct PartyJourneyTableHandle<'ctx> {
    imp: __sdk::TableHandle<PartyJourney>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `party_journey`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PartyJourneyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PartyJourneyTableHandle`], which mediates access to the table `party_journey`.
    fn party_journey(&self) -> PartyJourneyTableHandle<'_>;
}

impl PartyJourneyTableAccess for super::RemoteTables {
    fn party_journey(&self) -> PartyJourneyTableHandle<'_> {
        PartyJourneyTableHandle {
            imp: self.imp.get_table::<PartyJourney>("party_journey"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PartyJourneyInsertCallbackId(__sdk::CallbackId);
pub struct PartyJourneyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PartyJourneyTableHandle<'ctx> {
    type Row = PartyJourney;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyJourney> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PartyJourneyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyJourneyInsertCallbackId {
        PartyJourneyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyJourneyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PartyJourneyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyJourneyDeleteCallbackId {
        PartyJourneyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyJourneyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PartyJourneyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PartyJourneyTableHandle<'ctx> {
    type UpdateCallbackId = PartyJourneyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyJourneyUpdateCallbackId {
        PartyJourneyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyJourneyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `party_id` unique index on the table `party_journey`,
/// which allows point queries on the field of the same name
/// via the [`PartyJourneyPartyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_journey().party_id().find(...)`.
pub struct PartyJourneyPartyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PartyJourney, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PartyJourneyTableHandle<'ctx> {
    /// Get a handle on the `party_id` unique index on the table `party_journey`.
    pub fn party_id(&self) -> PartyJourneyPartyIdUnique<'ctx> {
        PartyJourneyPartyIdUnique {
            imp: self.imp.get_unique_constraint::<String>("party_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PartyJourneyPartyIdUnique<'ctx> {
    /// Find the subscribed row whose `party_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PartyJourney> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PartyJourney>("party_journey");
    _table.add_unique_constraint::<String>("party_id", |row| &row.party_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PartyJourney>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PartyJourney>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PartyJourney`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait party_journeyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PartyJourney`.
    fn party_journey(&self) -> __sdk::__query_builder::Table<PartyJourney>;
}

impl party_journeyQueryTableAccess for __sdk::QueryTableAccessor {
    fn party_journey(&self) -> __sdk::__query_builder::Table<PartyJourney> {
        __sdk::__query_builder::Table::new("party_journey")
    }
}
