// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PayOrganizationDuesArgs {
    pub character_id: u64,
    pub organization_id: String,
}

impl From<PayOrganizationDuesArgs> for super::Reducer {
    fn from(args: PayOrganizationDuesArgs) -> Self {
        Self::PayOrganizationDues {
            character_id: args.character_id,
            organization_id: args.organization_id,
        }
    }
}

impl __sdk::InModule for PayOrganizationDuesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pay_organization_dues`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pay_organization_dues {
    /// Request that the remote module invoke the reducer `pay_organization_dues` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pay_organization_dues:pay_organization_dues_then`] to run a callback after the reducer completes.
    fn pay_organization_dues(
        &self,
        character_id: u64,
        organization_id: String,
    ) -> __sdk::Result<()> {
        self.pay_organization_dues_then(character_id, organization_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pay_organization_dues` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pay_organization_dues_then(
        &self,
        character_id: u64,
        organization_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl pay_organization_dues for super::RemoteReducers {
    fn pay_organization_dues_then(
        &self,
        character_id: u64,
        organization_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PayOrganizationDuesArgs {
                character_id,
                organization_id,
            },
            callback,
        )
    }
}
