// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PerformInvestigationActionArgs {
    pub actor_id: u64,
    pub action_id: String,
    pub method: String,
    pub expected_version: u32,
}

impl From<PerformInvestigationActionArgs> for super::Reducer {
    fn from(args: PerformInvestigationActionArgs) -> Self {
        Self::PerformInvestigationAction {
            actor_id: args.actor_id,
            action_id: args.action_id,
            method: args.method,
            expected_version: args.expected_version,
}
}
}

impl __sdk::InModule for PerformInvestigationActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `perform_investigation_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait perform_investigation_action {
    /// Request that the remote module invoke the reducer `perform_investigation_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`perform_investigation_action:perform_investigation_action_then`] to run a callback after the reducer completes.
    fn perform_investigation_action(&self, actor_id: u64,
action_id: String,
method: String,
expected_version: u32,
) -> __sdk::Result<()> {
        self.perform_investigation_action_then(actor_id, action_id, method, expected_version,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `perform_investigation_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn perform_investigation_action_then(
        &self,
        actor_id: u64,
action_id: String,
method: String,
expected_version: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl perform_investigation_action for super::RemoteReducers {
    fn perform_investigation_action_then(
        &self,
        actor_id: u64,
action_id: String,
method: String,
expected_version: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PerformInvestigationActionArgs { actor_id, action_id, method, expected_version,  }, callback)
    }
}

