// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhysicalEvidenceInspectionActionReceipt {
    pub action_id: String,
    pub owner_character_id: u64,
    pub evidence_id: String,
    pub topic_id: String,
}

impl __sdk::InModule for PhysicalEvidenceInspectionActionReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PhysicalEvidenceInspectionActionReceipt`.
///
/// Provides typed access to columns for query building.
pub struct PhysicalEvidenceInspectionActionReceiptCols {
    pub action_id: __sdk::__query_builder::Col<PhysicalEvidenceInspectionActionReceipt, String>,
    pub owner_character_id:
        __sdk::__query_builder::Col<PhysicalEvidenceInspectionActionReceipt, u64>,
    pub evidence_id: __sdk::__query_builder::Col<PhysicalEvidenceInspectionActionReceipt, String>,
    pub topic_id: __sdk::__query_builder::Col<PhysicalEvidenceInspectionActionReceipt, String>,
}

impl __sdk::__query_builder::HasCols for PhysicalEvidenceInspectionActionReceipt {
    type Cols = PhysicalEvidenceInspectionActionReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PhysicalEvidenceInspectionActionReceiptCols {
            action_id: __sdk::__query_builder::Col::new(table_name, "action_id"),
            owner_character_id: __sdk::__query_builder::Col::new(table_name, "owner_character_id"),
            evidence_id: __sdk::__query_builder::Col::new(table_name, "evidence_id"),
            topic_id: __sdk::__query_builder::Col::new(table_name, "topic_id"),
        }
    }
}

/// Indexed column accessor struct for the table `PhysicalEvidenceInspectionActionReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct PhysicalEvidenceInspectionActionReceiptIxCols {
    pub action_id: __sdk::__query_builder::IxCol<PhysicalEvidenceInspectionActionReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for PhysicalEvidenceInspectionActionReceipt {
    type IxCols = PhysicalEvidenceInspectionActionReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PhysicalEvidenceInspectionActionReceiptIxCols {
            action_id: __sdk::__query_builder::IxCol::new(table_name, "action_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PhysicalEvidenceInspectionActionReceipt {}
