// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PrepareDevelopmentCourtshipArgs {
    pub suitor_id: u64,
    pub partner_id: u64,
}

impl From<PrepareDevelopmentCourtshipArgs> for super::Reducer {
    fn from(args: PrepareDevelopmentCourtshipArgs) -> Self {
        Self::PrepareDevelopmentCourtship {
            suitor_id: args.suitor_id,
            partner_id: args.partner_id,
        }
    }
}

impl __sdk::InModule for PrepareDevelopmentCourtshipArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `prepare_development_courtship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait prepare_development_courtship {
    /// Request that the remote module invoke the reducer `prepare_development_courtship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`prepare_development_courtship:prepare_development_courtship_then`] to run a callback after the reducer completes.
    fn prepare_development_courtship(&self, suitor_id: u64, partner_id: u64) -> __sdk::Result<()> {
        self.prepare_development_courtship_then(suitor_id, partner_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `prepare_development_courtship` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn prepare_development_courtship_then(
        &self,
        suitor_id: u64,
        partner_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl prepare_development_courtship for super::RemoteReducers {
    fn prepare_development_courtship_then(
        &self,
        suitor_id: u64,
        partner_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PrepareDevelopmentCourtshipArgs {
                suitor_id,
                partner_id,
            },
            callback,
        )
    }
}
