// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::world_clock_schedule_type::WorldClockSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RefreshWorldClockArgs {
    pub schedule: WorldClockSchedule,
}

impl From<RefreshWorldClockArgs> for super::Reducer {
    fn from(args: RefreshWorldClockArgs) -> Self {
        Self::RefreshWorldClock {
            schedule: args.schedule,
        }
    }
}

impl __sdk::InModule for RefreshWorldClockArgs {
    type Module = super::RemoteModule;
}

pub struct RefreshWorldClockCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `refresh_world_clock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait refresh_world_clock {
    /// Request that the remote module invoke the reducer `refresh_world_clock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_refresh_world_clock`] callbacks.
    fn refresh_world_clock(&self, schedule: WorldClockSchedule) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `refresh_world_clock`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RefreshWorldClockCallbackId`] can be passed to [`Self::remove_on_refresh_world_clock`]
    /// to cancel the callback.
    fn on_refresh_world_clock(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &WorldClockSchedule) + Send + 'static,
    ) -> RefreshWorldClockCallbackId;
    /// Cancel a callback previously registered by [`Self::on_refresh_world_clock`],
    /// causing it not to run in the future.
    fn remove_on_refresh_world_clock(&self, callback: RefreshWorldClockCallbackId);
}

impl refresh_world_clock for super::RemoteReducers {
    fn refresh_world_clock(&self, schedule: WorldClockSchedule) -> __sdk::Result<()> {
        self.imp
            .call_reducer("refresh_world_clock", RefreshWorldClockArgs { schedule })
    }
    fn on_refresh_world_clock(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &WorldClockSchedule) + Send + 'static,
    ) -> RefreshWorldClockCallbackId {
        RefreshWorldClockCallbackId(self.imp.on_reducer(
            "refresh_world_clock",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RefreshWorldClock { schedule },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, schedule)
            }),
        ))
    }
    fn remove_on_refresh_world_clock(&self, callback: RefreshWorldClockCallbackId) {
        self.imp
            .remove_on_reducer("refresh_world_clock", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `refresh_world_clock`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_refresh_world_clock {
    /// Set the call-reducer flags for the reducer `refresh_world_clock` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn refresh_world_clock(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_refresh_world_clock for super::SetReducerFlags {
    fn refresh_world_clock(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("refresh_world_clock", flags);
    }
}
