// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportContractArgs {
    pub character_id: u64,
    pub contract_id: String,
}

impl From<ReportContractArgs> for super::Reducer {
    fn from(args: ReportContractArgs) -> Self {
        Self::ReportContract {
            character_id: args.character_id,
            contract_id: args.contract_id,
        }
    }
}

impl __sdk::InModule for ReportContractArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_contract`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_contract {
    /// Request that the remote module invoke the reducer `report_contract` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`report_contract:report_contract_then`] to run a callback after the reducer completes.
    fn report_contract(&self, character_id: u64, contract_id: String) -> __sdk::Result<()> {
        self.report_contract_then(character_id, contract_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `report_contract` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn report_contract_then(
        &self,
        character_id: u64,
        contract_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl report_contract for super::RemoteReducers {
    fn report_contract_then(
        &self,
        character_id: u64,
        contract_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ReportContractArgs {
                character_id,
                contract_id,
            },
            callback,
        )
    }
}
