// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RetrieveFireplaceContainerArgs {
    pub character_id: u64,
    pub fireplace_fixture_id: String,
    pub container_object_id: u64,
}

impl From<RetrieveFireplaceContainerArgs> for super::Reducer {
    fn from(args: RetrieveFireplaceContainerArgs) -> Self {
        Self::RetrieveFireplaceContainer {
            character_id: args.character_id,
            fireplace_fixture_id: args.fireplace_fixture_id,
            container_object_id: args.container_object_id,
        }
    }
}

impl __sdk::InModule for RetrieveFireplaceContainerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `retrieve_fireplace_container`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait retrieve_fireplace_container {
    /// Request that the remote module invoke the reducer `retrieve_fireplace_container` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`retrieve_fireplace_container:retrieve_fireplace_container_then`] to run a callback after the reducer completes.
    fn retrieve_fireplace_container(
        &self,
        character_id: u64,
        fireplace_fixture_id: String,
        container_object_id: u64,
    ) -> __sdk::Result<()> {
        self.retrieve_fireplace_container_then(
            character_id,
            fireplace_fixture_id,
            container_object_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `retrieve_fireplace_container` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn retrieve_fireplace_container_then(
        &self,
        character_id: u64,
        fireplace_fixture_id: String,
        container_object_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl retrieve_fireplace_container for super::RemoteReducers {
    fn retrieve_fireplace_container_then(
        &self,
        character_id: u64,
        fireplace_fixture_id: String,
        container_object_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RetrieveFireplaceContainerArgs {
                character_id,
                fireplace_fixture_id,
                container_object_id,
            },
            callback,
        )
    }
}
