// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::water_distance_meters_type::WaterDistanceMeters;
use super::strahler_order_type::StrahlerOrder;
use super::flow_persistence_type::FlowPersistence;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RiverAccess {
    pub distance: WaterDistanceMeters,
    pub order: StrahlerOrder,
    pub persistence: FlowPersistence,
}


impl __sdk::InModule for RiverAccess {
    type Module = super::RemoteModule;
}

