// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedSickCharacterArgs {}

impl From<SeedSickCharacterArgs> for super::Reducer {
    fn from(args: SeedSickCharacterArgs) -> Self {
        Self::SeedSickCharacter
    }
}

impl __sdk::InModule for SeedSickCharacterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_sick_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_sick_character {
    /// Request that the remote module invoke the reducer `seed_sick_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_sick_character:seed_sick_character_then`] to run a callback after the reducer completes.
    fn seed_sick_character(&self) -> __sdk::Result<()> {
        self.seed_sick_character_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_sick_character` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_sick_character_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_sick_character for super::RemoteReducers {
    fn seed_sick_character_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedSickCharacterArgs {}, callback)
    }
}
