// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedPartyCompanionsArgs {
    pub leader_id: u64,
}

impl From<SeedPartyCompanionsArgs> for super::Reducer {
    fn from(args: SeedPartyCompanionsArgs) -> Self {
        Self::SeedPartyCompanions {
            leader_id: args.leader_id,
        }
    }
}

impl __sdk::InModule for SeedPartyCompanionsArgs {
    type Module = super::RemoteModule;
}

pub struct SeedPartyCompanionsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_party_companions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_party_companions {
    /// Request that the remote module invoke the reducer `seed_party_companions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_seed_party_companions`] callbacks.
    fn seed_party_companions(&self, leader_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `seed_party_companions`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SeedPartyCompanionsCallbackId`] can be passed to [`Self::remove_on_seed_party_companions`]
    /// to cancel the callback.
    fn on_seed_party_companions(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> SeedPartyCompanionsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_seed_party_companions`],
    /// causing it not to run in the future.
    fn remove_on_seed_party_companions(&self, callback: SeedPartyCompanionsCallbackId);
}

impl seed_party_companions for super::RemoteReducers {
    fn seed_party_companions(&self, leader_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "seed_party_companions",
            SeedPartyCompanionsArgs { leader_id },
        )
    }
    fn on_seed_party_companions(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> SeedPartyCompanionsCallbackId {
        SeedPartyCompanionsCallbackId(self.imp.on_reducer(
            "seed_party_companions",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SeedPartyCompanions { leader_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, leader_id)
            }),
        ))
    }
    fn remove_on_seed_party_companions(&self, callback: SeedPartyCompanionsCallbackId) {
        self.imp
            .remove_on_reducer("seed_party_companions", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `seed_party_companions`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_seed_party_companions {
    /// Set the call-reducer flags for the reducer `seed_party_companions` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn seed_party_companions(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_seed_party_companions for super::SetReducerFlags {
    fn seed_party_companions(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("seed_party_companions", flags);
    }
}
