// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedBotJoinRequestsArgs {
    pub party_id: String,
    pub count: u32,
}

impl From<SeedBotJoinRequestsArgs> for super::Reducer {
    fn from(args: SeedBotJoinRequestsArgs) -> Self {
        Self::SeedBotJoinRequests {
            party_id: args.party_id,
            count: args.count,
        }
    }
}

impl __sdk::InModule for SeedBotJoinRequestsArgs {
    type Module = super::RemoteModule;
}

pub struct SeedBotJoinRequestsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_bot_join_requests`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_bot_join_requests {
    /// Request that the remote module invoke the reducer `seed_bot_join_requests` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_seed_bot_join_requests`] callbacks.
    fn seed_bot_join_requests(&self, party_id: String, count: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `seed_bot_join_requests`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SeedBotJoinRequestsCallbackId`] can be passed to [`Self::remove_on_seed_bot_join_requests`]
    /// to cancel the callback.
    fn on_seed_bot_join_requests(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u32) + Send + 'static,
    ) -> SeedBotJoinRequestsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_seed_bot_join_requests`],
    /// causing it not to run in the future.
    fn remove_on_seed_bot_join_requests(&self, callback: SeedBotJoinRequestsCallbackId);
}

impl seed_bot_join_requests for super::RemoteReducers {
    fn seed_bot_join_requests(&self, party_id: String, count: u32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "seed_bot_join_requests",
            SeedBotJoinRequestsArgs { party_id, count },
        )
    }
    fn on_seed_bot_join_requests(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u32) + Send + 'static,
    ) -> SeedBotJoinRequestsCallbackId {
        SeedBotJoinRequestsCallbackId(self.imp.on_reducer(
            "seed_bot_join_requests",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SeedBotJoinRequests { party_id, count },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, party_id, count)
            }),
        ))
    }
    fn remove_on_seed_bot_join_requests(&self, callback: SeedBotJoinRequestsCallbackId) {
        self.imp
            .remove_on_reducer("seed_bot_join_requests", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `seed_bot_join_requests`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_seed_bot_join_requests {
    /// Set the call-reducer flags for the reducer `seed_bot_join_requests` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn seed_bot_join_requests(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_seed_bot_join_requests for super::SetReducerFlags {
    fn seed_bot_join_requests(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("seed_bot_join_requests", flags);
    }
}
