// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SelectBrowserCharacterArgs {
    pub owner_key: String,
    pub character_id: u64,
}

impl From<SelectBrowserCharacterArgs> for super::Reducer {
    fn from(args: SelectBrowserCharacterArgs) -> Self {
        Self::SelectBrowserCharacter {
            owner_key: args.owner_key,
            character_id: args.character_id,
        }
    }
}

impl __sdk::InModule for SelectBrowserCharacterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `select_browser_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait select_browser_character {
    /// Request that the remote module invoke the reducer `select_browser_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`select_browser_character:select_browser_character_then`] to run a callback after the reducer completes.
    fn select_browser_character(&self, owner_key: String, character_id: u64) -> __sdk::Result<()> {
        self.select_browser_character_then(owner_key, character_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `select_browser_character` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn select_browser_character_then(
        &self,
        owner_key: String,
        character_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl select_browser_character for super::RemoteReducers {
    fn select_browser_character_then(
        &self,
        owner_key: String,
        character_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SelectBrowserCharacterArgs {
                owner_key,
                character_id,
            },
            callback,
        )
    }
}
