// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SettlementNpcRelationship {
    pub id: String,
    pub observer_character_id: u64,
    pub npc_id: String,
    pub affinity_anchor: f32,
    pub affinity_anchor_minute: u64,
    pub shared_minutes: u64,
}

impl __sdk::InModule for SettlementNpcRelationship {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SettlementNpcRelationship`.
///
/// Provides typed access to columns for query building.
pub struct SettlementNpcRelationshipCols {
    pub id: __sdk::__query_builder::Col<SettlementNpcRelationship, String>,
    pub observer_character_id: __sdk::__query_builder::Col<SettlementNpcRelationship, u64>,
    pub npc_id: __sdk::__query_builder::Col<SettlementNpcRelationship, String>,
    pub affinity_anchor: __sdk::__query_builder::Col<SettlementNpcRelationship, f32>,
    pub affinity_anchor_minute: __sdk::__query_builder::Col<SettlementNpcRelationship, u64>,
    pub shared_minutes: __sdk::__query_builder::Col<SettlementNpcRelationship, u64>,
}

impl __sdk::__query_builder::HasCols for SettlementNpcRelationship {
    type Cols = SettlementNpcRelationshipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SettlementNpcRelationshipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            observer_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "observer_character_id",
            ),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            affinity_anchor: __sdk::__query_builder::Col::new(table_name, "affinity_anchor"),
            affinity_anchor_minute: __sdk::__query_builder::Col::new(
                table_name,
                "affinity_anchor_minute",
            ),
            shared_minutes: __sdk::__query_builder::Col::new(table_name, "shared_minutes"),
        }
    }
}

/// Indexed column accessor struct for the table `SettlementNpcRelationship`.
///
/// Provides typed access to indexed columns for query building.
pub struct SettlementNpcRelationshipIxCols {
    pub id: __sdk::__query_builder::IxCol<SettlementNpcRelationship, String>,
    pub npc_id: __sdk::__query_builder::IxCol<SettlementNpcRelationship, String>,
    pub observer_character_id: __sdk::__query_builder::IxCol<SettlementNpcRelationship, u64>,
}

impl __sdk::__query_builder::HasIxCols for SettlementNpcRelationship {
    type IxCols = SettlementNpcRelationshipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SettlementNpcRelationshipIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
            observer_character_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "observer_character_id",
            ),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SettlementNpcRelationship {}
