// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SettlementHerbalist {
    pub settlement_id: String,
    pub medicine_skill: u8,
}

impl __sdk::InModule for SettlementHerbalist {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SettlementHerbalist`.
///
/// Provides typed access to columns for query building.
pub struct SettlementHerbalistCols {
    pub settlement_id: __sdk::__query_builder::Col<SettlementHerbalist, String>,
    pub medicine_skill: __sdk::__query_builder::Col<SettlementHerbalist, u8>,
}

impl __sdk::__query_builder::HasCols for SettlementHerbalist {
    type Cols = SettlementHerbalistCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SettlementHerbalistCols {
            settlement_id: __sdk::__query_builder::Col::new(table_name, "settlement_id"),
            medicine_skill: __sdk::__query_builder::Col::new(table_name, "medicine_skill"),
        }
    }
}

/// Indexed column accessor struct for the table `SettlementHerbalist`.
///
/// Provides typed access to indexed columns for query building.
pub struct SettlementHerbalistIxCols {
    pub settlement_id: __sdk::__query_builder::IxCol<SettlementHerbalist, String>,
}

impl __sdk::__query_builder::HasIxCols for SettlementHerbalist {
    type IxCols = SettlementHerbalistIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SettlementHerbalistIxCols {
            settlement_id: __sdk::__query_builder::IxCol::new(table_name, "settlement_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SettlementHerbalist {}
