// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::settlement_description_kind_type::SettlementDescriptionKind;
use super::settlement_description_type::SettlementDescription;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `settlement_description`.
///
/// Obtain a handle from the [`SettlementDescriptionTableAccess::settlement_description`] method on [`super::RemoteTables`],
/// like `ctx.db.settlement_description()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.settlement_description().on_insert(...)`.
pub struct SettlementDescriptionTableHandle<'ctx> {
    imp: __sdk::TableHandle<SettlementDescription>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `settlement_description`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SettlementDescriptionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SettlementDescriptionTableHandle`], which mediates access to the table `settlement_description`.
    fn settlement_description(&self) -> SettlementDescriptionTableHandle<'_>;
}

impl SettlementDescriptionTableAccess for super::RemoteTables {
    fn settlement_description(&self) -> SettlementDescriptionTableHandle<'_> {
        SettlementDescriptionTableHandle {
            imp: self
                .imp
                .get_table::<SettlementDescription>("settlement_description"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SettlementDescriptionInsertCallbackId(__sdk::CallbackId);
pub struct SettlementDescriptionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SettlementDescriptionTableHandle<'ctx> {
    type Row = SettlementDescription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SettlementDescription> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SettlementDescriptionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettlementDescriptionInsertCallbackId {
        SettlementDescriptionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SettlementDescriptionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SettlementDescriptionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettlementDescriptionDeleteCallbackId {
        SettlementDescriptionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SettlementDescriptionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SettlementDescriptionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SettlementDescriptionTableHandle<'ctx> {
    type UpdateCallbackId = SettlementDescriptionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SettlementDescriptionUpdateCallbackId {
        SettlementDescriptionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SettlementDescriptionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `settlement_description`,
/// which allows point queries on the field of the same name
/// via the [`SettlementDescriptionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.settlement_description().id().find(...)`.
pub struct SettlementDescriptionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SettlementDescription, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SettlementDescriptionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `settlement_description`.
    pub fn id(&self) -> SettlementDescriptionIdUnique<'ctx> {
        SettlementDescriptionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SettlementDescriptionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SettlementDescription> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SettlementDescription>("settlement_description");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SettlementDescription>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SettlementDescription>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SettlementDescription`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait settlement_descriptionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SettlementDescription`.
    fn settlement_description(&self) -> __sdk::__query_builder::Table<SettlementDescription>;
}

impl settlement_descriptionQueryTableAccess for __sdk::QueryTableAccessor {
    fn settlement_description(&self) -> __sdk::__query_builder::Table<SettlementDescription> {
        __sdk::__query_builder::Table::new("settlement_description")
    }
}
