// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agricultural_limitation_type::AgriculturalLimitation;
use super::available_water_capacity_type::AvailableWaterCapacity;
use super::soil_depth_type::SoilDepth;
use super::soil_material_type::SoilMaterial;
use super::soil_water_regime_type::SoilWaterRegime;
use super::stone_content_percent_type::StoneContentPercent;
use super::topsoil_organic_carbon_type::TopsoilOrganicCarbon;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SoilProperties {
    pub material: SoilMaterial,
    pub depth: SoilDepth,
    pub available_water: AvailableWaterCapacity,
    pub organic_carbon: TopsoilOrganicCarbon,
    pub water_regime: SoilWaterRegime,
    pub stones: StoneContentPercent,
    pub agricultural_limitation: AgriculturalLimitation,
}

impl __sdk::InModule for SoilProperties {
    type Module = super::RemoteModule;
}
