// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::strategic_incident_type::StrategicIncident;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `strategic_incident`.
///
/// Obtain a handle from the [`StrategicIncidentTableAccess::strategic_incident`] method on [`super::RemoteTables`],
/// like `ctx.db.strategic_incident()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.strategic_incident().on_insert(...)`.
pub struct StrategicIncidentTableHandle<'ctx> {
    imp: __sdk::TableHandle<StrategicIncident>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `strategic_incident`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StrategicIncidentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StrategicIncidentTableHandle`], which mediates access to the table `strategic_incident`.
    fn strategic_incident(&self) -> StrategicIncidentTableHandle<'_>;
}

impl StrategicIncidentTableAccess for super::RemoteTables {
    fn strategic_incident(&self) -> StrategicIncidentTableHandle<'_> {
        StrategicIncidentTableHandle {
            imp: self
                .imp
                .get_table::<StrategicIncident>("strategic_incident"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StrategicIncidentInsertCallbackId(__sdk::CallbackId);
pub struct StrategicIncidentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StrategicIncidentTableHandle<'ctx> {
    type Row = StrategicIncident;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StrategicIncident> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StrategicIncidentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StrategicIncidentInsertCallbackId {
        StrategicIncidentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StrategicIncidentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StrategicIncidentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StrategicIncidentDeleteCallbackId {
        StrategicIncidentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StrategicIncidentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StrategicIncidentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StrategicIncidentTableHandle<'ctx> {
    type UpdateCallbackId = StrategicIncidentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StrategicIncidentUpdateCallbackId {
        StrategicIncidentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StrategicIncidentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `quest_id` unique index on the table `strategic_incident`,
/// which allows point queries on the field of the same name
/// via the [`StrategicIncidentQuestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.strategic_incident().quest_id().find(...)`.
pub struct StrategicIncidentQuestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StrategicIncident, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StrategicIncidentTableHandle<'ctx> {
    /// Get a handle on the `quest_id` unique index on the table `strategic_incident`.
    pub fn quest_id(&self) -> StrategicIncidentQuestIdUnique<'ctx> {
        StrategicIncidentQuestIdUnique {
            imp: self.imp.get_unique_constraint::<String>("quest_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StrategicIncidentQuestIdUnique<'ctx> {
    /// Find the subscribed row whose `quest_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<StrategicIncident> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StrategicIncident>("strategic_incident");
    _table.add_unique_constraint::<String>("quest_id", |row| &row.quest_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StrategicIncident>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StrategicIncident>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StrategicIncident`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait strategic_incidentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StrategicIncident`.
    fn strategic_incident(&self) -> __sdk::__query_builder::Table<StrategicIncident>;
}

impl strategic_incidentQueryTableAccess for __sdk::QueryTableAccessor {
    fn strategic_incident(&self) -> __sdk::__query_builder::Table<StrategicIncident> {
        __sdk::__query_builder::Table::new("strategic_incident")
    }
}
