// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SynchronizeCharacterTimeArgs {
    pub character_id: u64,
}

impl From<SynchronizeCharacterTimeArgs> for super::Reducer {
    fn from(args: SynchronizeCharacterTimeArgs) -> Self {
        Self::SynchronizeCharacterTime {
            character_id: args.character_id,
}
}
}

impl __sdk::InModule for SynchronizeCharacterTimeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `synchronize_character_time`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait synchronize_character_time {
    /// Request that the remote module invoke the reducer `synchronize_character_time` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`synchronize_character_time:synchronize_character_time_then`] to run a callback after the reducer completes.
    fn synchronize_character_time(&self, character_id: u64,
) -> __sdk::Result<()> {
        self.synchronize_character_time_then(character_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `synchronize_character_time` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn synchronize_character_time_then(
        &self,
        character_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl synchronize_character_time for super::RemoteReducers {
    fn synchronize_character_time_then(
        &self,
        character_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SynchronizeCharacterTimeArgs { character_id,  }, callback)
    }
}

