// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SynchronizePartyForActivityArgs {
    pub leader_id: u64,
}

impl From<SynchronizePartyForActivityArgs> for super::Reducer {
    fn from(args: SynchronizePartyForActivityArgs) -> Self {
        Self::SynchronizePartyForActivity {
            leader_id: args.leader_id,
        }
    }
}

impl __sdk::InModule for SynchronizePartyForActivityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `synchronize_party_for_activity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait synchronize_party_for_activity {
    /// Request that the remote module invoke the reducer `synchronize_party_for_activity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`synchronize_party_for_activity:synchronize_party_for_activity_then`] to run a callback after the reducer completes.
    fn synchronize_party_for_activity(&self, leader_id: u64) -> __sdk::Result<()> {
        self.synchronize_party_for_activity_then(leader_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `synchronize_party_for_activity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn synchronize_party_for_activity_then(
        &self,
        leader_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl synchronize_party_for_activity for super::RemoteReducers {
    fn synchronize_party_for_activity_then(
        &self,
        leader_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SynchronizePartyForActivityArgs { leader_id }, callback)
    }
}
