// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TrackCaseSiteArgs {
    pub character_id: u64,
    pub case_site_id: String,
}

impl From<TrackCaseSiteArgs> for super::Reducer {
    fn from(args: TrackCaseSiteArgs) -> Self {
        Self::TrackCaseSite {
            character_id: args.character_id,
            case_site_id: args.case_site_id,
        }
    }
}

impl __sdk::InModule for TrackCaseSiteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `track_case_site`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait track_case_site {
    /// Request that the remote module invoke the reducer `track_case_site` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`track_case_site:track_case_site_then`] to run a callback after the reducer completes.
    fn track_case_site(&self, character_id: u64, case_site_id: String) -> __sdk::Result<()> {
        self.track_case_site_then(character_id, case_site_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `track_case_site` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn track_case_site_then(
        &self,
        character_id: u64,
        case_site_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl track_case_site for super::RemoteReducers {
    fn track_case_site_then(
        &self,
        character_id: u64,
        case_site_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TrackCaseSiteArgs {
                character_id,
                case_site_id,
            },
            callback,
        )
    }
}
