// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TransferPartyItemArgs {
    pub from_character_id: u64,
    pub to_character_id: u64,
    pub inventory_item_id: u64,
    pub quantity: u32,
}

impl From<TransferPartyItemArgs> for super::Reducer {
    fn from(args: TransferPartyItemArgs) -> Self {
        Self::TransferPartyItem {
            from_character_id: args.from_character_id,
            to_character_id: args.to_character_id,
            inventory_item_id: args.inventory_item_id,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for TransferPartyItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `transfer_party_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait transfer_party_item {
    /// Request that the remote module invoke the reducer `transfer_party_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`transfer_party_item:transfer_party_item_then`] to run a callback after the reducer completes.
    fn transfer_party_item(
        &self,
        from_character_id: u64,
        to_character_id: u64,
        inventory_item_id: u64,
        quantity: u32,
    ) -> __sdk::Result<()> {
        self.transfer_party_item_then(
            from_character_id,
            to_character_id,
            inventory_item_id,
            quantity,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `transfer_party_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn transfer_party_item_then(
        &self,
        from_character_id: u64,
        to_character_id: u64,
        inventory_item_id: u64,
        quantity: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl transfer_party_item for super::RemoteReducers {
    fn transfer_party_item_then(
        &self,
        from_character_id: u64,
        to_character_id: u64,
        inventory_item_id: u64,
        quantity: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TransferPartyItemArgs {
                from_character_id,
                to_character_id,
                inventory_item_id,
                quantity,
            },
            callback,
        )
    }
}
