// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::edge_endpoint_type::EdgeEndpoint;
use super::travel_edge_type::TravelEdge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `travel_edge`.
///
/// Obtain a handle from the [`TravelEdgeTableAccess::travel_edge`] method on [`super::RemoteTables`],
/// like `ctx.db.travel_edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.travel_edge().on_insert(...)`.
pub struct TravelEdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<TravelEdge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `travel_edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TravelEdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TravelEdgeTableHandle`], which mediates access to the table `travel_edge`.
    fn travel_edge(&self) -> TravelEdgeTableHandle<'_>;
}

impl TravelEdgeTableAccess for super::RemoteTables {
    fn travel_edge(&self) -> TravelEdgeTableHandle<'_> {
        TravelEdgeTableHandle {
            imp: self.imp.get_table::<TravelEdge>("travel_edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TravelEdgeInsertCallbackId(__sdk::CallbackId);
pub struct TravelEdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TravelEdgeTableHandle<'ctx> {
    type Row = TravelEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TravelEdge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TravelEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TravelEdgeInsertCallbackId {
        TravelEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TravelEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TravelEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TravelEdgeDeleteCallbackId {
        TravelEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TravelEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TravelEdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TravelEdgeTableHandle<'ctx> {
    type UpdateCallbackId = TravelEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TravelEdgeUpdateCallbackId {
        TravelEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TravelEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `travel_edge`,
/// which allows point queries on the field of the same name
/// via the [`TravelEdgeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.travel_edge().id().find(...)`.
pub struct TravelEdgeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TravelEdge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TravelEdgeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `travel_edge`.
    pub fn id(&self) -> TravelEdgeIdUnique<'ctx> {
        TravelEdgeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TravelEdgeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TravelEdge> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TravelEdge>("travel_edge");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TravelEdge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TravelEdge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TravelEdge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait travel_edgeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TravelEdge`.
    fn travel_edge(&self) -> __sdk::__query_builder::Table<TravelEdge>;
}

impl travel_edgeQueryTableAccess for __sdk::QueryTableAccessor {
    fn travel_edge(&self) -> __sdk::__query_builder::Table<TravelEdge> {
        __sdk::__query_builder::Table::new("travel_edge")
    }
}
