// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePartyCheckTargetsArgs {
    pub leader_id: u64,
    pub medicine: f32,
    pub surgery: f32,
    pub charisma: f32,
    pub faith: f32,
}

impl From<UpdatePartyCheckTargetsArgs> for super::Reducer {
    fn from(args: UpdatePartyCheckTargetsArgs) -> Self {
        Self::UpdatePartyCheckTargets {
            leader_id: args.leader_id,
            medicine: args.medicine,
            surgery: args.surgery,
            charisma: args.charisma,
            faith: args.faith,
        }
    }
}

impl __sdk::InModule for UpdatePartyCheckTargetsArgs {
    type Module = super::RemoteModule;
}

pub struct UpdatePartyCheckTargetsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_party_check_targets`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_party_check_targets {
    /// Request that the remote module invoke the reducer `update_party_check_targets` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_party_check_targets`] callbacks.
    fn update_party_check_targets(
        &self,
        leader_id: u64,
        medicine: f32,
        surgery: f32,
        charisma: f32,
        faith: f32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_party_check_targets`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdatePartyCheckTargetsCallbackId`] can be passed to [`Self::remove_on_update_party_check_targets`]
    /// to cancel the callback.
    fn on_update_party_check_targets(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &f32, &f32, &f32, &f32) + Send + 'static,
    ) -> UpdatePartyCheckTargetsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_party_check_targets`],
    /// causing it not to run in the future.
    fn remove_on_update_party_check_targets(&self, callback: UpdatePartyCheckTargetsCallbackId);
}

impl update_party_check_targets for super::RemoteReducers {
    fn update_party_check_targets(
        &self,
        leader_id: u64,
        medicine: f32,
        surgery: f32,
        charisma: f32,
        faith: f32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_party_check_targets",
            UpdatePartyCheckTargetsArgs {
                leader_id,
                medicine,
                surgery,
                charisma,
                faith,
            },
        )
    }
    fn on_update_party_check_targets(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &f32, &f32, &f32, &f32)
            + Send
            + 'static,
    ) -> UpdatePartyCheckTargetsCallbackId {
        UpdatePartyCheckTargetsCallbackId(self.imp.on_reducer(
            "update_party_check_targets",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdatePartyCheckTargets {
                                    leader_id,
                                    medicine,
                                    surgery,
                                    charisma,
                                    faith,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, leader_id, medicine, surgery, charisma, faith)
            }),
        ))
    }
    fn remove_on_update_party_check_targets(&self, callback: UpdatePartyCheckTargetsCallbackId) {
        self.imp
            .remove_on_reducer("update_party_check_targets", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_party_check_targets`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_party_check_targets {
    /// Set the call-reducer flags for the reducer `update_party_check_targets` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_party_check_targets(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_party_check_targets for super::SetReducerFlags {
    fn update_party_check_targets(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_party_check_targets", flags);
    }
}
