// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::schedule_allocation_type::ScheduleAllocation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateTrainingScheduleArgs {
    pub character_id: u64,
    pub downtime: ScheduleAllocation,
}

impl From<UpdateTrainingScheduleArgs> for super::Reducer {
    fn from(args: UpdateTrainingScheduleArgs) -> Self {
        Self::UpdateTrainingSchedule {
            character_id: args.character_id,
            downtime: args.downtime,
        }
    }
}

impl __sdk::InModule for UpdateTrainingScheduleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_training_schedule`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_training_schedule {
    /// Request that the remote module invoke the reducer `update_training_schedule` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_training_schedule:update_training_schedule_then`] to run a callback after the reducer completes.
    fn update_training_schedule(
        &self,
        character_id: u64,
        downtime: ScheduleAllocation,
    ) -> __sdk::Result<()> {
        self.update_training_schedule_then(character_id, downtime, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_training_schedule` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_training_schedule_then(
        &self,
        character_id: u64,
        downtime: ScheduleAllocation,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_training_schedule for super::RemoteReducers {
    fn update_training_schedule_then(
        &self,
        character_id: u64,
        downtime: ScheduleAllocation,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateTrainingScheduleArgs {
                character_id,
                downtime,
            },
            callback,
        )
    }
}
