// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateCharacterArgs {
    pub id: u64,
    pub name: String,
}

impl From<UpdateCharacterArgs> for super::Reducer {
    fn from(args: UpdateCharacterArgs) -> Self {
        Self::UpdateCharacter {
            id: args.id,
            name: args.name,
        }
    }
}

impl __sdk::InModule for UpdateCharacterArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateCharacterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_character {
    /// Request that the remote module invoke the reducer `update_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_character`] callbacks.
    fn update_character(&self, id: u64, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_character`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateCharacterCallbackId`] can be passed to [`Self::remove_on_update_character`]
    /// to cancel the callback.
    fn on_update_character(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> UpdateCharacterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_character`],
    /// causing it not to run in the future.
    fn remove_on_update_character(&self, callback: UpdateCharacterCallbackId);
}

impl update_character for super::RemoteReducers {
    fn update_character(&self, id: u64, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_character", UpdateCharacterArgs { id, name })
    }
    fn on_update_character(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> UpdateCharacterCallbackId {
        UpdateCharacterCallbackId(self.imp.on_reducer(
            "update_character",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateCharacter { id, name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, name)
            }),
        ))
    }
    fn remove_on_update_character(&self, callback: UpdateCharacterCallbackId) {
        self.imp.remove_on_reducer("update_character", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_character`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_character {
    /// Set the call-reducer flags for the reducer `update_character` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_character(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_character for super::SetReducerFlags {
    fn update_character(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_character", flags);
    }
}
