// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WaterHoldingContribution {
    pub id: String,
    pub holding_key: String,
    pub material_lot_id: u64,
    pub amount_microliters: u64,
    pub contaminant_load_microunits: u64,
    pub collected_at: u64,
}

impl __sdk::InModule for WaterHoldingContribution {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WaterHoldingContribution`.
///
/// Provides typed access to columns for query building.
pub struct WaterHoldingContributionCols {
    pub id: __sdk::__query_builder::Col<WaterHoldingContribution, String>,
    pub holding_key: __sdk::__query_builder::Col<WaterHoldingContribution, String>,
    pub material_lot_id: __sdk::__query_builder::Col<WaterHoldingContribution, u64>,
    pub amount_microliters: __sdk::__query_builder::Col<WaterHoldingContribution, u64>,
    pub contaminant_load_microunits: __sdk::__query_builder::Col<WaterHoldingContribution, u64>,
    pub collected_at: __sdk::__query_builder::Col<WaterHoldingContribution, u64>,
}

impl __sdk::__query_builder::HasCols for WaterHoldingContribution {
    type Cols = WaterHoldingContributionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WaterHoldingContributionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            holding_key: __sdk::__query_builder::Col::new(table_name, "holding_key"),
            material_lot_id: __sdk::__query_builder::Col::new(table_name, "material_lot_id"),
            amount_microliters: __sdk::__query_builder::Col::new(table_name, "amount_microliters"),
            contaminant_load_microunits: __sdk::__query_builder::Col::new(
                table_name,
                "contaminant_load_microunits",
            ),
            collected_at: __sdk::__query_builder::Col::new(table_name, "collected_at"),
        }
    }
}

/// Indexed column accessor struct for the table `WaterHoldingContribution`.
///
/// Provides typed access to indexed columns for query building.
pub struct WaterHoldingContributionIxCols {
    pub holding_key: __sdk::__query_builder::IxCol<WaterHoldingContribution, String>,
    pub id: __sdk::__query_builder::IxCol<WaterHoldingContribution, String>,
}

impl __sdk::__query_builder::HasIxCols for WaterHoldingContribution {
    type IxCols = WaterHoldingContributionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WaterHoldingContributionIxCols {
            holding_key: __sdk::__query_builder::IxCol::new(table_name, "holding_key"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WaterHoldingContribution {}
