// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WithdrawPartyInventoryItemArgs {
    pub character_id: u64,
    pub party_inventory_item_id: u64,
    pub quantity: u32,
}

impl From<WithdrawPartyInventoryItemArgs> for super::Reducer {
    fn from(args: WithdrawPartyInventoryItemArgs) -> Self {
        Self::WithdrawPartyInventoryItem {
            character_id: args.character_id,
            party_inventory_item_id: args.party_inventory_item_id,
            quantity: args.quantity,
}
}
}

impl __sdk::InModule for WithdrawPartyInventoryItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `withdraw_party_inventory_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait withdraw_party_inventory_item {
    /// Request that the remote module invoke the reducer `withdraw_party_inventory_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`withdraw_party_inventory_item:withdraw_party_inventory_item_then`] to run a callback after the reducer completes.
    fn withdraw_party_inventory_item(&self, character_id: u64,
party_inventory_item_id: u64,
quantity: u32,
) -> __sdk::Result<()> {
        self.withdraw_party_inventory_item_then(character_id, party_inventory_item_id, quantity,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `withdraw_party_inventory_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn withdraw_party_inventory_item_then(
        &self,
        character_id: u64,
party_inventory_item_id: u64,
quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl withdraw_party_inventory_item for super::RemoteReducers {
    fn withdraw_party_inventory_item_then(
        &self,
        character_id: u64,
party_inventory_item_id: u64,
quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(WithdrawPartyInventoryItemArgs { character_id, party_inventory_item_id, quantity,  }, callback)
    }
}

