// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WitnessSocialCooldown {
    pub id: String,
    pub observer_character_id: u64,
    pub npc_id: String,
    pub action_kind: String,
    pub available_at_minute: u64,
}

impl __sdk::InModule for WitnessSocialCooldown {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WitnessSocialCooldown`.
///
/// Provides typed access to columns for query building.
pub struct WitnessSocialCooldownCols {
    pub id: __sdk::__query_builder::Col<WitnessSocialCooldown, String>,
    pub observer_character_id: __sdk::__query_builder::Col<WitnessSocialCooldown, u64>,
    pub npc_id: __sdk::__query_builder::Col<WitnessSocialCooldown, String>,
    pub action_kind: __sdk::__query_builder::Col<WitnessSocialCooldown, String>,
    pub available_at_minute: __sdk::__query_builder::Col<WitnessSocialCooldown, u64>,
}

impl __sdk::__query_builder::HasCols for WitnessSocialCooldown {
    type Cols = WitnessSocialCooldownCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WitnessSocialCooldownCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            observer_character_id: __sdk::__query_builder::Col::new(
                table_name,
                "observer_character_id",
            ),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            action_kind: __sdk::__query_builder::Col::new(table_name, "action_kind"),
            available_at_minute: __sdk::__query_builder::Col::new(
                table_name,
                "available_at_minute",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `WitnessSocialCooldown`.
///
/// Provides typed access to indexed columns for query building.
pub struct WitnessSocialCooldownIxCols {
    pub id: __sdk::__query_builder::IxCol<WitnessSocialCooldown, String>,
}

impl __sdk::__query_builder::HasIxCols for WitnessSocialCooldown {
    type IxCols = WitnessSocialCooldownIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WitnessSocialCooldownIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WitnessSocialCooldown {}
