#!/usr/bin/env python3
"""Generate wiki/SUMMARY.md from the explicit wiki navigation manifest."""

from __future__ import annotations

import argparse
import difflib
import os
from pathlib import Path
import tempfile
import tomllib
from typing import Any


REPOSITORY = Path(__file__).resolve().parent.parent
WIKI = REPOSITORY / "wiki"
MANIFEST = WIKI / "navigation.toml"
SUMMARY = WIKI / "SUMMARY.md"


class NavigationError(ValueError):
    """The navigation manifest cannot produce a safe, complete summary."""


def _require_string(item: dict[str, Any], key: str, index: int) -> str:
    value = item.get(key)
    if not isinstance(value, str) or not value.strip():
        raise NavigationError(f"item {index}: {key!r} must be a non-empty string")
    if "\n" in value or "\r" in value:
        raise NavigationError(f"item {index}: {key!r} must fit on one line")
    return value


def _resolve_page(path_text: str, index: int) -> Path:
    path = Path(path_text)
    if path.is_absolute() or path.suffix.lower() != ".md":
        raise NavigationError(
            f"item {index}: page path must be a relative Markdown path: {path_text!r}"
        )
    resolved = (WIKI / path).resolve()
    try:
        resolved.relative_to(REPOSITORY.resolve())
    except ValueError as error:
        raise NavigationError(
            f"item {index}: page escapes the repository: {path_text!r}"
        ) from error
    if not resolved.is_file():
        raise NavigationError(f"item {index}: page does not exist: {path_text!r}")
    return resolved


def _append_blank(lines: list[str]) -> None:
    if lines and lines[-1] != "":
        lines.append("")


def load_and_render(manifest_path: Path = MANIFEST) -> str:
    try:
        data = tomllib.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise NavigationError(f"cannot read {manifest_path}: {error}") from error

    unknown_top_level = set(data) - {"format_version", "excluded", "item"}
    if unknown_top_level:
        raise NavigationError(
            "unknown top-level keys: " + ", ".join(sorted(unknown_top_level))
        )
    if data.get("format_version") != 1:
        raise NavigationError("format_version must be 1")

    items = data.get("item")
    if not isinstance(items, list) or not items:
        raise NavigationError("the manifest must contain at least one [[item]]")

    lines = [
        "<!-- Generated by scripts/update_wiki_summary.py from navigation.toml. -->",
        "",
        "# Summary",
        "",
    ]
    listed_pages: set[Path] = set()

    for index, item in enumerate(items, start=1):
        if not isinstance(item, dict):
            raise NavigationError(f"item {index}: expected a table")
        kind = item.get("kind")

        if kind == "part":
            unknown = set(item) - {"kind", "title"}
            if unknown:
                raise NavigationError(
                    f"item {index}: unknown part keys: {', '.join(sorted(unknown))}"
                )
            title = _require_string(item, "title", index)
            _append_blank(lines)
            lines.extend((f"# {title}", ""))
            continue

        if kind == "separator":
            unknown = set(item) - {"kind"}
            if unknown:
                raise NavigationError(
                    f"item {index}: unknown separator keys: {', '.join(sorted(unknown))}"
                )
            _append_blank(lines)
            lines.extend(("---", ""))
            continue

        if kind != "page":
            raise NavigationError(
                f"item {index}: kind must be 'page', 'part', or 'separator'"
            )

        unknown = set(item) - {"kind", "title", "path", "bullet", "depth"}
        if unknown:
            raise NavigationError(
                f"item {index}: unknown page keys: {', '.join(sorted(unknown))}"
            )
        title = _require_string(item, "title", index)
        path_text = _require_string(item, "path", index)
        if any(character in title for character in "[]"):
            raise NavigationError(f"item {index}: title cannot contain '[' or ']'")
        resolved = _resolve_page(path_text, index)
        if resolved in listed_pages:
            raise NavigationError(f"item {index}: page is listed more than once: {path_text}")
        listed_pages.add(resolved)

        bullet = item.get("bullet", True)
        depth = item.get("depth", 0)
        if not isinstance(bullet, bool):
            raise NavigationError(f"item {index}: bullet must be true or false")
        if not isinstance(depth, int) or isinstance(depth, bool) or depth < 0:
            raise NavigationError(f"item {index}: depth must be a non-negative integer")
        if not bullet and depth:
            raise NavigationError(f"item {index}: an unbulleted page cannot have depth")

        prefix = ("    " * depth + "- ") if bullet else ""
        lines.append(f"{prefix}[{title}]({path_text})")

    excluded_value = data.get("excluded", [])
    if not isinstance(excluded_value, list) or not all(
        isinstance(path, str) for path in excluded_value
    ):
        raise NavigationError("excluded must be an array of relative Markdown paths")

    excluded_pages: set[Path] = set()
    for path_text in excluded_value:
        resolved = _resolve_page(path_text, 0)
        try:
            resolved.relative_to(WIKI.resolve())
        except ValueError as error:
            raise NavigationError(
                f"excluded page must be inside wiki/: {path_text!r}"
            ) from error
        if resolved == SUMMARY.resolve():
            raise NavigationError("SUMMARY.md is excluded automatically")
        if resolved in listed_pages:
            raise NavigationError(f"page is both listed and excluded: {path_text!r}")
        if resolved in excluded_pages:
            raise NavigationError(f"page is excluded more than once: {path_text!r}")
        excluded_pages.add(resolved)

    wiki_pages = {
        path.resolve()
        for path in WIKI.rglob("*.md")
        if path.resolve() != SUMMARY.resolve()
    }
    accounted_for = {
        path for path in listed_pages | excluded_pages if path.is_relative_to(WIKI.resolve())
    }
    unaccounted = wiki_pages - accounted_for
    if unaccounted:
        names = ", ".join(
            str(path.relative_to(WIKI.resolve())) for path in sorted(unaccounted)
        )
        raise NavigationError(f"wiki pages are neither listed nor excluded: {names}")

    if lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def update(*, check: bool = False) -> bool:
    rendered = load_and_render()
    current = SUMMARY.read_text(encoding="utf-8") if SUMMARY.exists() else ""
    if current == rendered:
        print(f"{SUMMARY.relative_to(REPOSITORY)} is current.")
        return True
    if check:
        diff = difflib.unified_diff(
            current.splitlines(),
            rendered.splitlines(),
            fromfile=str(SUMMARY.relative_to(REPOSITORY)),
            tofile="generated SUMMARY.md",
            lineterm="",
        )
        print("\n".join(diff))
        return False

    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=WIKI, delete=False
    ) as temporary:
        temporary.write(rendered)
        temporary_path = Path(temporary.name)
    try:
        os.replace(temporary_path, SUMMARY)
    finally:
        temporary_path.unlink(missing_ok=True)
    print(f"Updated {SUMMARY.relative_to(REPOSITORY)}.")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if SUMMARY.md differs from the validated manifest",
    )
    arguments = parser.parse_args()
    try:
        return 0 if update(check=arguments.check) else 1
    except NavigationError as error:
        parser.error(str(error))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
