[package]
name = "adventuresim-world-schema"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
spacetimedb = ["dep:spacetimedb"]

[dependencies]
serde.workspace = true
spacetimedb = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
