//! Renders a [`Resolver`]'s discovered classes as Python source, matching
//! the exact layout `scripts/adventuresim_brp_lib.py` needs (see
//! `just generate-brp-types` and wiki/reference/tactical-testing.md).

use crate::resolve::{Body, ClassDef, Resolver, StructKind};

pub fn render(resolver: &Resolver) -> String {
    let mut lines: Vec<String> = Vec::new();
    print_header(&mut lines);
    print_base_classes(&mut lines);
    print_section(&mut lines, resolver, StructKind::Component, "# Components");
    print_section(&mut lines, resolver, StructKind::Resource, "# Resources");
    print_section(
        &mut lines,
        resolver,
        StructKind::Nested,
        "# Nested/helper types",
    );

    let mut output = lines.join("\n");
    output.push('\n');
    output
}

fn print_header(lines: &mut Vec<String>) {
    for line in [
        "\"\"\"Auto-generated by `just generate-brp-types` - do not edit by hand.",
        "",
        "Every BRP-queryable (`ReflectComponent`/`ReflectResource`) type linked in",
        "from `adventuresim-tactical-server`/`-client`, discovered dynamically from",
        "the real `AppTypeRegistry` (see crates/adventuresim-tactical-brp-generator) - not",
        "a hand-maintained list. Re-run `just generate-brp-types` after adding,",
        "renaming, or moving a `#[reflect(Component)]`/`#[reflect(Resource)]` type.",
        "\"\"\"",
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Any, ClassVar, Literal",
    ] {
        lines.push(line.to_string());
    }
}

fn print_base_classes(lines: &mut Vec<String>) {
    for line in [
        "",
        "# Base classes shared by every generated Components/Resources class below.",
        "# `type_path` is what BRP identifies the type by on the wire; `to_brp()`/",
        "# `from_brp()` convert between an instance and the exact JSON value BRP",
        "# sends/expects for it. `BrpClient`'s component/resource-shaped methods (see",
        "# tactical_brp.py) take and return these, not raw type-path strings or dicts.",
        "",
        "class BevyComponent:",
        "    type_path: ClassVar[str]",
        "",
        "    def to_brp(self) -> object:",
        "        raise NotImplementedError",
        "",
        "    @classmethod",
        "    def from_brp(cls, value: object) -> \"BevyComponent\":",
        "        raise NotImplementedError",
        "",
        "",
        "class BevyResource:",
        "    type_path: ClassVar[str]",
        "",
        "    def to_brp(self) -> object:",
        "        raise NotImplementedError",
        "",
        "    @classmethod",
        "    def from_brp(cls, value: object) -> \"BevyResource\":",
        "        raise NotImplementedError",
    ] {
        lines.push(line.to_string());
    }
}

fn print_section(lines: &mut Vec<String>, resolver: &Resolver, kind: StructKind, marker: &str) {
    lines.push(String::new());
    lines.push(marker.to_string());

    for class in resolver.classes.values().filter(|c| c.kind == kind) {
        lines.push(String::new());
        lines.push("@dataclass".to_string());
        render_class(class, lines);
    }
}

fn render_class(class: &ClassDef, lines: &mut Vec<String>) {
    let header = match class.kind {
        StructKind::Component => format!("class {}(BevyComponent):", class.class_name),
        StructKind::Resource => format!("class {}(BevyResource):", class.class_name),
        StructKind::Nested => format!("class {}:", class.class_name),
    };
    lines.push(header);
    lines.push(format!("    \"\"\"`{}`\"\"\"", class.type_path));
    if class.kind != StructKind::Nested {
        lines.push(format!(
            "    type_path: ClassVar[str] = \"{}\"",
            class.type_path
        ));
    }

    match &class.body {
        Body::Fields(fields) => render_fields_class(class, fields, lines),
        Body::Transparent(encoding) => render_transparent_class(class, encoding, lines),
    }
}

fn render_fields_class(
    class: &ClassDef,
    fields: &[crate::resolve::FieldDef],
    lines: &mut Vec<String>,
) {
    for field in fields {
        let comment = field
            .encoding
            .comment()
            .map(|c| format!("  {c}"))
            .unwrap_or_default();
        let ident = crate::resolve::python_ident(&field.name);
        lines.push(format!(
            "    {}: {}{}",
            ident,
            field.encoding.annotation(),
            comment
        ));
    }

    lines.push(String::new());
    lines.push("    def to_brp(self) -> object:".to_string());
    lines.push("        return {".to_string());
    for field in fields {
        let mut depth = 0u32;
        let ident = crate::resolve::python_ident(&field.name);
        let expr = field
            .encoding
            .to_brp_expr(&format!("self.{ident}"), &mut depth);
        lines.push(format!("            \"{}\": {},", field.name, expr));
    }
    lines.push("        }".to_string());

    lines.push(String::new());
    lines.push("    @classmethod".to_string());
    lines.push(format!(
        "    def from_brp(cls, value: object) -> \"{}\":",
        class.class_name
    ));
    lines.push("        data = value".to_string());
    lines.push("        assert isinstance(data, dict)".to_string());
    lines.push("        return cls(".to_string());
    for field in fields {
        let mut depth = 0u32;
        let expr = field
            .encoding
            .from_brp_expr(&format!("data[\"{}\"]", field.name), &mut depth);
        let ident = crate::resolve::python_ident(&field.name);
        lines.push(format!("            {}={},", ident, expr));
    }
    lines.push("        )".to_string());
}

fn render_transparent_class(
    class: &ClassDef,
    encoding: &crate::resolve::Encoding,
    lines: &mut Vec<String>,
) {
    let comment = encoding
        .comment()
        .map(|c| format!("  {c}"))
        .unwrap_or_default();
    lines.push(format!("    value: {}{}", encoding.annotation(), comment));

    lines.push(String::new());
    lines.push("    def to_brp(self) -> object:".to_string());
    let mut depth = 0u32;
    let expr = encoding.to_brp_expr("self.value", &mut depth);
    lines.push(format!("        return {expr}"));

    lines.push(String::new());
    lines.push("    @classmethod".to_string());
    lines.push(format!(
        "    def from_brp(cls, value: object) -> \"{}\":",
        class.class_name
    ));
    let mut depth = 0u32;
    let expr = encoding.from_brp_expr("value", &mut depth);
    lines.push(format!("        return cls(value={expr})"));
}
