[package]
name = "adventuresim-tactical-core"
description = "Adventure Simulator: Tactical layer core library"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
meshgen = ["bevy/bevy_mesh"]

[dependencies]
adventuresim-core.workspace = true
bevy = { workspace = true, features = ["bevy_color"] }
serde.workspace = true
bevy_enhanced_input.workspace = true
avian3d.workspace = true
bevy_ahoy.workspace = true
strum = { version = "0.28", features = ["derive"] }
bitflags = "2.11.0"

[lints]
workspace = true
